### ISSUE TITLE
Edge case in Fall Mountain if you grab the crown at the same time than someone else.

### ISSUE THREAD

**Issue by NikoUY** [ShootMe/FallGuysStats#10]
If you grab the crown at the same time than someone else and it shows your celebration the game will try to go to the reward screen but it won't be able to do it and after a few seconds the client will disconnect from the server, the tracker won't register it.

Here are the logs:
[Player-prev.log](https://gist.github.com/NikoUY/053367721e09cdeeae45012a347b9ee4)
[Player.log](https://gist.github.com/NikoUY/2c11add2409124a005ef0f9a1423645e)

At the end of Player-prev.log (I restarted the game to get the crown after I got disconnected) it shows that I won the round and also it shows the crash so I'm guessing you should be able to catch this edge case.

[Here](https://drive.google.com/drive/folders/1UpxbLZqKQliILuWirzrQ8kk1PJWNl4nA?usp=sharing) are the db files, keep in mind I played one game before I realized that I should submit a report and I won the previous final on Fall Mountain (if you look at the time you will notice that it's not the same game).

**Comment by ShootMe** [comment]
It's actually quite hard to account for that, it's actually why a bunch of people had messed up stats about 2 weeks ago, cause I was checking for the results from the server but wasn't verifying when they came. It can come at any point when playing and it would screw up the logic and cause a lot of problems, so I made it so you had to get the results at the end of the show or I would ignore it. It might be possible to do something for your case, but I wouldn't want to mess with it much without possibly screwing up stats again for normal games.

I can move things around in your log file to make it record that game for you if that's something you'd want. You'd then just make sure the game is closed and make it Player.log and open the tracker and it should add just that one show.

**Comment by NikoUY** [comment]
I appreciate that you took the time to fix the log, thanks, it was added correctly after I did what you said, anyways it's not really an issue for me I just thought it was worth reporting it, for now on I'll just add one to the previous game counter if I encounter this issue like I did for this round before you fixed the log.

**Comment by ShootMe** [comment]
I think Ill close this now. Not going try and mess with adding special logic to account for this.
