### ISSUE TITLE
Ping value is not being updated

### ISSUE THREAD

**Issue by jraspante** [ShootMe/FallGuysStats#100]
I don't know if it is happening only with me or a small group of users, but my friend and I are having this issue.

The first time I open the game, the ping is being updated. But all the others shows, the ping is the same than the last round of the first show. Even if I reopen the stats again, the same ping is there. 
It sounds a bit confuse, but it was the behavior that I observed so far.

**Comment by aadmaquino** [comment]
I'm having the same issue... 😕 Could you fix it, please?

**Comment by asriznet** [comment]
with the new feature where it shows a connection icon bottom right when someone has bad connection, wouldnt it have some real time info somewhere to write these values somewhere?

**Comment by jraspante** [comment]
@asriznet I believe it is not possible, once this feature is in-game. They are not writing the ping value very often in logs files anymore
