### ISSUE TITLE
Ping indicator freezes after some time

### ISSUE THREAD

**Issue by jl456lj** [ShootMe/FallGuysStats#103]
Not sure if it's been reported yet, but I notice that after the season 4.5 update, sometimes the ping display just freezes after playing the game for a while and won't update when I change to servers with a different ping. Not sure if it's a problem with the tracker or it's due to some changes within the code of the game.

**Comment by ropbl4** [comment]
I have the same problem 2 days ago.

**Comment by bexwhitt** [comment]
I think this is more on Fall Guys  than the tracker as they changed something that breaks the ping

**Comment by jraspante** [comment]
I recently opened a related issue #100.
The game doesn't update the log file with the ping after some time. So there is nothing they can do to fix it.

It started to happen after the 4.5 update, I hope they write it again in season 5.
