### ISSUE TITLE
Overlay Corrupted

### ISSUE THREAD

**Issue by karateman10998** [ShootMe/FallGuysStats#104]
I'm not sure what happened to my overlay but it became extremely small and unreadable. It's still the same length but the height got smooshed. If I replace the db file it fixes the issue but I lose all my stats. Is there a way to reset the overlay?

**Comment by ShootMe** [comment]
Just check/uncheck one of the Hide options in the settings for the overlay then save then put it back and save again. Should be normal size

**Comment by karateman10998** [comment]
Thank you!!!
