### ISSUE TITLE
overlay shows all for gold/qualify even when set to solo

### ISSUE THREAD

**Issue by BryantLuu** [ShootMe/FallGuysStats#11]
The overlay shows all for gold and qualify stat even when set to solo

**Comment by ShootMe** [comment]
Yea, I currently have it showing the stats for all time for Qualify and Gold. I will probably add a setting to choose what it should show in the near future.

**Comment by BryantLuu** [comment]
wouldn't it be consistent with the other stats if it changed depending on the filter like the rest of the overlay?

**Comment by ShootMe** [comment]
Some people wanted those stats to be all time regardless of filter. I've added more options in the settings screen now (1.49) for you to choose how it works.
