### ISSUE TITLE
Tool is not updating to latest version 

### ISSUE THREAD

**Issue by ageric4** [ShootMe/FallGuysStats#114]
I have been on v1.117 since last June. When I hit the update button in the app, it sends me to the Github page for this tool, but I don't see any instructions for how to update to the latest version. Maybe it's something simple, or maybe I'm blind, but I'd appreciate any advice if I'm missing something. Thanks!

**Comment by ShootMe** [comment]
You have the manual update version, you have to download the new version manually by just copying the exe and replacing your existing one

**Comment by ageric4** [comment]
Yep, that was it. Thank you so much. Forgot I used the manual version initially.
