### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by xShiller** [ShootMe/FallGuysStats#12]
I'm receiving [this](https://i.imgur.com/1hYZlav.png) error upon loading the program. And my timed played is in [the negatives](https://i.imgur.com/Nfd6vnc.png)
I got the log files this time.
[Player.log](https://github.com/ShootMe/FallGuysStats/files/5180634/Player.log)
[Player-prev.log](https://github.com/ShootMe/FallGuysStats/files/5180636/Player-prev.log)

**Comment by ShootMe** [comment]
If you just started using the program go ahead and redownload the version I just fixed (1.51).  You can then just run the program and it should read the logs correctly. If you had previous data, upload your data.db and Ill fix it.

**Comment by xShiller** [comment]
Here it is, thank you. [data.zip](https://github.com/ShootMe/FallGuysStats/files/5180947/data.zip)

**Comment by ShootMe** [comment]
Make sure to grab 1.51 before opening the program again. And here is the fixed data.db 
[data.zip](https://github.com/ShootMe/FallGuysStats/files/5180972/data.zip)

**Comment by xShiller** [comment]
Works well, ty
