### ISSUE TITLE
Suggestion: more flexible overlay 

### ISSUE THREAD

**Issue by quaz33** [ShootMe/FallGuysStats#127]
The settings for the overlay could be more flexible and easier to understand. Instead of having 3 columns with different sub settings for each - how about 3x3 slots. With each the user can select one of the stats via drop down. And the 9 slot options again. If one is selected, the overlay rotates between the selected stats.

**Comment by ShootMe** [comment]
It's kind of what I wanted to do originally, but I just don't have the time/energy to work on this project anymore beyond very minor things like adding new levels.
