### ISSUE TITLE
[Feature Request] A way to see your win % per map in the main window

### ISSUE THREAD

**Issue by NikoUY** [ShootMe/FallGuysStats#13]
Currently the only way to see it is in the overlay when you are playing that map, there should be a way to see it in the main app, maybe the win% on top could be made clickable and a new window will appear that shows your win % per map (maybe with a trending column that compares the last 5-10 games and shows you the how much it changed in the last 5-10 games would be cool too) or you could just add another column in the main table.

**Comment by ShootMe** [comment]
As a quick change I can just add a tool tip (hover mouse) on the Qualified column on the main screen that shows it. And maybe add extra functionality when I get more time.

**Comment by NikoUY** [comment]
Thanks, that works fine, you can close this issue unless you want to add something else.
By the way I don't think is worth opening another issue but the delete functionality doesn't work, you can't select a cell, the issue is in [this](https://github.com/ShootMe/FallGuysStats/blob/8e0556e30d5f1e4fa19bf471a5583fb218b24485/Views/LevelDetails.cs#L160) line, if you delete "&& gridDetails.SelectedCells.Count > 0" it works.

**Comment by ShootMe** [comment]
v1.65 has the ability to click the Win% label, which will toggle how the main grid displays. Either percentages or counts. Don't think I will do anything more complex than that.

**Comment by NikoUY** [comment]
Thanks, that's perfect!
