### ISSUE TITLE
Cant Open a new path with epic games launcher

### ISSUE THREAD

**Issue by Najplayslool** [ShootMe/FallGuysStats#135]
hello, I have a problem where I tried to put the path to the epic games launcher but... it didn't do anything,
so please add one for the epic games launcher ty.

**Comment by ohgeetee** [comment]
I have the same issue.  Clicking browse button returns error "The path is not of a legal form"

I'm on latest version of Windows 11

**Comment by McNinj** [comment]
Same here

**Comment by cosscoss** [comment]
same on epic

**Comment by AymericKing** [comment]
Same

**Comment by RHVGamer** [comment]
same

**Comment by Almaz-Kabirov** [comment]
sane

**Comment by Dhi207** [comment]
the issue got fixed just update the program and everything will be fine
