### ISSUE TITLE
Season 8 update

### ISSUE THREAD

**Issue by 123JLaney123** [ShootMe/FallGuysStats#138]
Needs updating for season 8 levels

**Comment by 123JLaney123** [comment]
Worth noting that Leading Light is appearing as a new round for some reason

**Comment by jonjbm** [comment]
I just updated to the new v1.127 for this season. Thanks for the quick update!

I still have a few games recorded from maps that aren't properly identified in the program -- they're likely from some of the beta sessions I played in. I'm not sure what the proper names of these maps are. They are named as followed at the bottom of my program:

Bluejay Event 01
Bluejay Event 02
Bluejay Event 03 Final
Follow-The-Leader Ss2 Launch

Would it be possible for you to make the program properly identify these? Would be much appreciated. Thanks again.

**Comment by adamkelly86** [comment]
> I just updated to the new v1.127 for this season. Thanks for the quick update!
> 
> I still have a few games recorded from maps that aren't properly identified in the program -- they're likely from some of the beta sessions I played in. I'm not sure what the proper names of these maps are. They are named as followed at the bottom of my program:
> 
> Bluejay Event 01 Bluejay Event 02 Bluejay Event 03 Final 
Bluejay Events are actually called "Bean Hill Zone" - not sure if the map is called differently when / once it goes into the show rotation

> Follow-The-Leader Ss2 Launch
Cannot confirm this one I'm afraid 

> Would it be possible for you to make the program properly identify these? Would be much appreciated. Thanks again.

**Comment by 123JLaney123** [comment]
Thanks for the update @ShootMe but the season filter is still applying itself to the start of season 7. As well as the issues mentioned above.

**Comment by ShootMe** [comment]
I can fix the season filter easily, but I have no real easy way of dealing with the other levels at the time being

**Comment by adamkelly86** [comment]
Follow-The-Leader SS2 Launch is Leading Light 

Gist of player logs for show where it's the second one is available here: 
https://gist.github.com/adamkelly86/0558504e38c0d53a2320fe5166307f19

**Comment by jonjbm** [comment]
> Follow-The-Leader SS2 Launch is Leading Light
Ah, cool. Thanks for figuring it out. 🙂

**Comment by ShootMe** [comment]
Hopefully fixed Leading Light in 129
