### ISSUE TITLE
so my timers are all on 0 and N/A even after launching the game through it

### ISSUE THREAD

**Issue by Maxthebuild** [ShootMe/FallGuysStats#149]
![image](https://user-images.githubusercontent.com/116585922/197582369-b2e1953c-edff-4ff6-bab9-290b03f90e08.png)

**Comment by Maxthebuild** [comment]
please help it says all on 0 and N/A even after i launch the game through fall guys stats

**Comment by adamkelly86** [comment]
Known issue due to log file changes used to parse - see 141  for updates
