### ISSUE TITLE
Export function

### ISSUE THREAD

**Issue by Grischabock** [ShootMe/FallGuysStats#15]
Would be very nice if there would be an export function in html or bbcode and preferably per show and total. That would be very exciting, especially for forum users. Thanks for a check

**Comment by ShootMe** [comment]
I'd probably need an example of what you want, and I assume you are talking about from the Rounds details screen, or Shows?

**Comment by kowzzz** [comment]
![image](https://user-images.githubusercontent.com/20546286/93228295-f17ebc00-f73a-11ea-85ef-fe920e14ed61.png)

`[table]
[tr]
	[th]Level Name[/th]
	[th]Played[/th]
	[th]Qualified[/th]
	[th]Gold[/th]
	[th]Silver[/th]
	[th]Bronze[/th]
	[th]Kudos[/th]
	[th]Avg Kudos[/th]
	[th]Avg Duration[/th]
[/tr]
[tr]
	[td]Fruit Chute[/td]
	[td]30[/td]
	[td]29[/td]
	[td]6[/td]
	[td]11[/td]
	[td]7[/td]
	[td]3405[/td]
	[td]113[/td]
	[td]0:43[/td]
[/tr]
[tr]
	[td]See Saw[/td]
	[td]30[/td]
	[td]30[/td]
	[td]9[/td]
	[td]15[/td]
	[td]6[/td]
	[td]3065[/td]
	[td]102[/td]
	[td]2:16[/td]
[/tr]
[/table]
`

Something like that is my guess. That way you can take the values and paste them into an Excel document and sort them around and stuff.

**Comment by Grischabock** [comment]
Hello, yes as a .csv it works, that's right. But if you want to export the whole thing for a website or forum then you first have to convert the .csv into html and copy everything out and insert a header.

The export should of course use the filters, so I want to export a session then it only exports this. But that works with .csv and should also be possible with html export, right?

Actually this html output would be the right one, yes. Simply export directly if possible.

[table] [tr] [th] Level Name [/ th] [th] Played [/ th] [th] Qualified [/ th] [th] Gold [/ th] [th] Silver [/ th] [th] Bronze [/ th] [th] Kudos [/ th] [th] Avg Kudos [/ th] [th] Avg Duration [/ th] [/ tr] [tr] [td] Fruit Chute [/ td] [td] 30 [/ td] [td] 29 [/ td] [td] 6 [/ td] [td] 11 [/ td] [td] 7 [/ td] [td] 3405 [/ td] [td] 113 [ / td] [td] 0:43 [/ td] [/ tr] [tr] [td] See Saw [/ td] [td] 30 [/ td] [td] 30 [/ td] [td] 9 [ / td] [td] 15 [/ td] [td] 6 [/ td] [td] 3065 [/ td] [td] 102 [/ td] [td] 2:16 [/ td] [/ tr] [ / table]

**Comment by ShootMe** [comment]
Ok I have added Html and BBCode options to the right click menu on the grids, which will export to your clipboard.
Can be found in v1.63

**Comment by Grischabock** [comment]
wow super many thanks, it works wonderfully. Would it be possible to include the title line as well? So Level Name, Played, Qualified ...

**Comment by ShootMe** [comment]
It should already include the header, unless you are talking about something else?

**Comment by Grischabock** [comment]
Also table yes, unfortunately not as BBCode.
