### ISSUE TITLE
Tracker suddenly stopped working (v1.130)

### ISSUE THREAD

**Issue by 123JLaney123** [ShootMe/FallGuysStats#152]
Tracker was working great after the v1.130 update, then suddenly? Nothing. It refuses to read anything at all. No idea why because nothing in the game/tracker has changed since then? I've tried a random assortment/combination of things such as:

- Verifying the integrity of the Steam game files
- Restarting my PC 
- Opening the tracker before, during, and after the opening the game (I know you're meant to do it before, I was just checking)
- Re-downloading the tracker and testing the newly downloaded version
- Downloading the "manual update" version of the tracker and testing that
- Setting the log path manually
- Changing the Fall Guys game location from "FallGuys_client_game" to "FallGuys_client" and back (what is the difference between those?)

Nothing worked. It worked perfectly before but now? Nothing.

I'm going to go ahead and also tag @ThreesFG as I had this exact same issue with his version of the tracker and never figured out why it doesn't work.

**Comment by mrsilverhawk** [comment]
same it doesnt work again after the fix.

**Comment by Letrobro** [comment]
ye for other people its working but not me to

**Comment by 123JLaney123** [comment]
I've just been told Mediatonic changed the log formats again, and this is why it doesn't work.

**Comment by amagus** [comment]
Mediatonic suddenly started relying on the user date format to print in the logs, but not consistently. So, in parts of the logs the date format is printed as yours, and in parts as the default one from the game (mm/dd/yyyy). 
Temporary solution is to set your Windows region to the same as the default from the game (we tested and recommend using English (US) as regional format).
Anyway, I don't have time to fix the parser, but it shouldn't be hard to adjust it to detect both date formats.

**Comment by 123JLaney123** [comment]
Con confirm the above workaround.

**Comment by Letrobro** [comment]
my fg is australia and my settings is australia but still doesn't work

**Comment by amagus** [comment]
You need to set it to United States and English (US). Australian english
will not work, even if your game is set to australian english.

**Comment by mrsilverhawk** [comment]
Will setting windows to US english mess with keyboard settings? Like im in norway and we got 3 more letters than the US. Will it work still?

**Comment by amagus** [comment]
It may mess up your keyboard. Blame microsoft. Anyway, you should be able
to go to keyboard settings and reconfigure it.

Or you should wait for someone to come up with a patch… this is just a
temporary workaround.

**Comment by Letrobro** [comment]
like this ?
![image](https://user-images.githubusercontent.com/117124085/201761447-3179dcd2-4aa4-4afb-9e3e-77ddc84c6afa.png)

**Comment by ThreesFG** [comment]
I can confirm what @amagus said above, it looks like the log (when using a regional formal like United Kingdom) writes the date as dd/MM/YYYY except when you start a game, and then it suddenly shifts to MM/dd/YYYY for the duration of the game. 🤷‍♂️ . Should be fixable.

**Comment by Letrobro** [comment]
YES ITS WORKING NOW THANKS

**Comment by ThreesFG** [comment]
I have submitted a pull request that should fix this issue: https://github.com/ShootMe/FallGuysStats/pull/153
