### ISSUE TITLE
Season 9 update

### ISSUE THREAD

**Issue by 123JLaney123** [ShootMe/FallGuysStats#154]
Needs the new levels and new season filter updating, please and thanks.

**Comment by ThreesFG** [comment]
It appears that Fall Guys fixed the issue with the timestamps not being in the logs! We should test reverting the code to version 1.129, as none of the code I submitted in the last two patches makes any sense if actual log times are back.

**Comment by iku55** [comment]
1.129 works fine in my environment!
This is my fork https://github.com/iku55/FallGuysStats

**Comment by adamkelly86** [comment]
Testing looks like its behaving correctly and pulling the rounds accordingly.

**Comment by 123JLaney123** [comment]
![image](https://user-images.githubusercontent.com/76238470/203494275-4bae7cb0-8998-4413-b3b4-4bbf693139df.png)
Slight issue
