### ISSUE TITLE
Overlay not showing up

### ISSUE THREAD

**Issue by kyborek** [ShootMe/FallGuysStats#16]
Hello.

When i first started up Fall Guys Stats and used it i was on 3 screens. I have opened the overlay and moved it to one of the screens.
Now when i have my PC on different place with only 1 or 2 screens i can not open the overlay. When i click the button nothing seemingly happens except that the Stats window looses focus.

I think that the overlay saves it's last position and it shows again at that same position which is now offscreen.

1. Is there a way to work around this to bring overlay back? Like deleting some kind of config (but i don't want to loose stats)
2. Could you please fix it such that there is a way to reset overlay position?
3. Best solution would be if the app memorized the number and resolution of available screens and reset the overlay position only when the configuration changes.

Thank you in advance for your help.

**Comment by ShootMe** [comment]
Hi there!

I just released 1.61, which will check the overlay's screen position and reset it if that is offscreen. Saving multiple configurations is a bit too complex of a feature for me to want to add, so I will just reset it instead. Hopefully that is good enough.
