### ISSUE TITLE
[Request test] Profile edit option and multilingual option

### ISSUE THREAD

**Issue by qutrits** [ShootMe/FallGuysStats#162]
Uploaded on February 7, 2023 at 13:50 (GMT+9)
[FallGuysStats 1.133 Multilingual Ver.zip](https://github.com/ShootMe/FallGuysStats/files/10697060/FallGuysStats.1.133.Multilingual.Ver.zip)
<br>
While using the FallGuysStats program well, I modified things that I personally wish I needed.

Once first,
While directly using the "Create / edit profiles" item uploaded in pull requests, various bug fixes and features were added.

1. Added option to display profile in overlay in settings.
2. Added various shortcut keys while the overlay is in focus.
2.1 'P' key : Toggle profiles in sequence.
2.2 Number 1~9 keys: Select profiles from 1 to 9.
2.3 Shift + Mouse Wheel: Toggles up and down the profile.
2.4 Shift + up and down arrow keys : Toggle the profile up and down.

3. Added option to store the number of users per console and display it in a grid (table).

4. Added multilingual options. There may be awkward parts because Japanese was helped by Google Translate. (Currently available in English, Korean and Japanese)

6. Fixed option to auto-launch Fall Guys client in FallGuysStats. This requires registering the Epic Games Fall Guys shortcut file in Settings.

After testing enough, I'm going to do a pull request.
Feedback is appreciated.
<br>

**[Notes]
The size of the program code itself is not much different than before, but the size of the program has increased significantly because the fonts include Japanese and Chinese characters.**
<br>
<br>
<br>

\+ Jan 31, 2023 23:25 (GMT+9)
Fixed a bug where each round was recognized as a final in Finals Marathon mode and the win and final were counted.
The blastball mod has the same issue, but currently there is no log data for the blastball mod, so it will be fixed when the next blast ball mod returns.

<br>
<br>
+ Feb 1, 2023 03:19 (GMT+9)<br>
Fixed finals and win count bugs for below modes.
but testing is not possible because the mode is not currently active.

- Finals Marathon
- Hex-a-gone Trials
- Hex-a-Gravity Trials
- Hex-a-thon
- Blast Ball Trials
<br>
<br>
+ Feb 1, 2023 15:10 (GMT+9)<br>
When running stats, if there is data from the previous show, a profile can be selected and saved.

<br>
<br>
<br>
+ Feb 6, 2023 22:10 (GMT+9)<br>
I applied the default font for each language. And minor bug fixes.
Also, there is a grid keystroke bug in the current release version, so I commented out the code.

<br>
<br>
<br>
+ Feb 7, 2023 13:50 (GMT+9)<br>
For all show IDs that have been released so far, show names have been mapped to match English, Korean, and Japanese.

<br>
<br>
<br>
+ Feb 7, 2023 23:37 (GMT+9)<br>
Added option to display color by round type.

**Comment by iku55** [comment]
Thanks for your contribution.

I can't download zip.
Could you please upload the zip in another way?

If you are in trouble, I can help you with the Japanese translation.

Here is list of round ids:
**Hex-a-gone Trials**
r1: round_floor_fall_event_only_01
r2: round_floor_fall_event_only_02
final: round_floor_fall_event_only_final
**Hex-a-Gravity Trials**
r1: round_floor_fall_event_only_low_grav_01
r2: round_floor_fall_event_only_low_grav_02
final: round_floor_fall_event_only_low_grav_final
**Hex-a-thon**
r1: round_floor_fall_event_walnut
r2: round_floor_fall_event_walnut_r2
final: round_floor_fall_event_walnut
r1: round_hexaring_event_walnut
r2: round_hexaring_event_walnut_r2
final: round_hexaring_event_walnut_final
r1: round_hexsnake_event_walnut
r2: round_hexsnake_event_walnut_r2
final: round_hexsnake_event_walnut_final
**Blast Ball Trials**
r1: round_blastball_arenasurvival_blast_ball_trials_01
r2: round_blastball_arenasurvival_blast_ball_trials_02
final: round_blastball_arenasurvival_blast_ball_trials_fn

**Comment by qutrits** [comment]
[FallGuysStats 1.133 Multilingual Ver.zip](https://github.com/ShootMe/FallGuysStats/files/10549532/FallGuysStats.1.133.Multilingual.Ver.zip)

@iku55 I added exception handling code for each mode with the data you provided, but testing is not possible because the mode is not currently active.

**Comment by qutrits** [comment]
+ Feb 1, 2023 15:10
When running stats, if there is data from the previous show, a profile can be selected and saved.

[FallGuysStats 1.133 Multilingual Ver.zip](https://github.com/ShootMe/FallGuysStats/files/10553806/FallGuysStats.1.133.Multilingual.Ver.zip)

**Comment by qutrits** [comment]
@iku55 Do you have a list of mod ids? Below is all I have.

- main_show [Solo Show]
- squads_2player_template [Duos Show]
- squads_4player [Squads Show]
- event_only_races_any_final_template [Day at the Races Solo]
- event_only_finals_v2_template [Finals Marathon]

**Comment by iku55** [comment]
> @iku55 Isn't the last round in "Hex-a-thon" mode "round_floor_fall_event_walnut_final" instead of "round_floor_fall_event_walnut"? And for "Blast Ball Trials", is it correct that the last round is appended with "_fn"?

Sorry, Hex-a-thon is a mistake
final: round_floor_fall_event_walnut -> round_floor_fall_event_walnut_final
"_fn" in "Blast Ball Trials" is correct.

Here is Japanese translation suggestions:
--Stats--
クドス -> Kudos
勝つ -> 勝利 or 勝利数
--Level Details--
ランク -> 順位
人員 -> 人数
--Overlay--
n ラウンド -> ラウンド n
--Edit Profiles--
登録 -> 追加
--Settings--
Statsス自動更新 -> Statsを自動更新 or 自動更新
Statsを実行するときにポールガイズクライアントも一緒に実行する -> Statsを実行するときにFallGuysも一緒に実行する

[Show list](http://iku55.starfree.jp/fg_temp_20230201/shows.html)
[Round list](http://iku55.starfree.jp/fg_temp_20230201/levels_round.html)
Please note that there are shows/rounds that are not used.
I will send you an easy-to-understand list tomorrow or the day after tomorrow

I've been busy lately and may not be able to debug or reply right away.

**Comment by qutrits** [comment]
@iku55 A 403 error page is exposed due to lack of access.

**Comment by iku55** [comment]
Please try again. 
I'll send you the HTML just in case.
[list.zip](https://github.com/ShootMe/FallGuysStats/files/10555018/list.zip)

**Comment by qutrits** [comment]
@iku55 I edited and uploaded it in Japanese that you suggested.
[FallGuysStats 1.133 Multilingual Ver.zip](https://github.com/ShootMe/FallGuysStats/files/10555288/FallGuysStats.1.133.Multilingual.Ver.zip)

**Comment by qutrits** [comment]
@iku55 I am working on mapping the name of the show into Korean. Could you help me with the Japanese mapping?

**Comment by iku55** [comment]
Here is my advices.

> @iku55 I am working on mapping the name of the show into Korean. Could you help me with the Japanese mapping? [Fall Guys show name translation](https://docs.google.com/spreadsheets/d/1Ex8mj223qu75ILASBGVvoju9sKn42uGGkhwv4s5WekE/edit#gid=0)
1. I can give you the names of all the shows in Japanese and Korean, but I don't think it's a good idea to update them every time a show is added.

2. Japanese translation suggestions:
--Main--
フィルタリング -> フィルタ
全体 -> すべて
プロフィール -> プロファイル
プロフィール設定 -> プロファイル設定
統計を表示 -> オーバーレイ
統計を隠す -> オーバーレイ
--Settings--
*Statsがログファイルパスを見つけられない場合は、ここにポールガイズクライアントのログファイルパスを直接入力してください。 -> *Statsがログファイルパスを見つけられない場合は、ここにFallGuysクライアントのログファイルパスを直接入力してください。
Stats -> 統計
フォントの選... -> フォント選択
フォントの初... -> リセット
セーブ -> 保存
--Profile Settings--
修正 -> 名前を変更
移動する -> データを移動

3. In the data migrated from the old version, the number of people by platform is displayed as "0", but I think "-" or "" is better.

4. settings version has not changed. Should change for compatibility (22->23)

**Comment by qutrits** [comment]
Uploaded on February 2, 2023 at 23:12 (GMT+9)
[FallGuysStats 1.133 Multilingual Ver.zip](https://github.com/ShootMe/FallGuysStats/files/10571080/FallGuysStats.1.133.Multilingual.Ver.zip)

@iku55 First of all, I applied the font only to the overlay. Please check how it is.

**Comment by iku55** [comment]
sorry, I made some mistakes in translation.
Japanese translation suggestions:
--Main--
統計を表示 -> オーバーレイ -> オーバーレイを表示
統計を隠す -> オーバーレイ -> オーバーレイを隠す
--Overlay--
ピン -> ping

> Can you tell me some popular free fonts that look good in Japanese?

I recommend Noto Sans JP because of the font used in Fall Guys.
Also, change the overlay default font back to Titan or change it for each language.

> I didn't understand what exactly the settings version meant in 4.

When you change the DB, you should change the user settings version like [this commit](https://github.com/ShootMe/FallGuysStats/commit/6b09168a209f91772371f7c6c748ef1ac3588c7a).

> It is necessary to map the ID of the show in English, Korean, and Japanese.

Okay.. If there are more shows in the future, I may not be able to give you show names, but is that okay?
[Shows (English)](http://iku55.starfree.jp/fg_temp_20230203/shows_en.html)
[Shows (Japanese)](http://iku55.starfree.jp/fg_temp_20230203/shows_ja.html)
[Shows (Korean)](http://iku55.starfree.jp/fg_temp_20230203/shows_kr.html)
[Rounds (English)](http://iku55.starfree.jp/fg_temp_20230203/levels_round_en.html)
[Rounds (Japanese)](http://iku55.starfree.jp/fg_temp_20230203/levels_round_ja.html)
[Rounds (Korean)](http://iku55.starfree.jp/fg_temp_20230203/levels_round_kr.html)
(I deleted the data I sent on February 1st.)

**Comment by qutrits** [comment]
@iku55 Like the last time, the 403 error page is being exposed because there is no permission.

**Comment by qutrits** [comment]
Uploaded on February 6, 2023 at 2
[FallGuysStats 1.133 Multilingual Ver.zip](https://github.com/ShootMe/FallGuysStats/files/10663347/FallGuysStats.1.133.Multilingual.Ver.zip)
2:10 (GMT+9)

As you suggested, I applied the default font for each language. And minor bug fixes.
Also, there is a grid keystroke bug in the current release version, so I commented out the code.

**Comment by iku55** [comment]
Here is html: [html.zip](https://github.com/ShootMe/FallGuysStats/files/10671401/html.zip)

**Comment by qutrits** [comment]
Uploaded on February 7, 2023 at 13:50 (GMT+9)
[FallGuysStats 1.133 Multilingual Ver.zip](https://github.com/ShootMe/FallGuysStats/files/10671634/FallGuysStats.1.133.Multilingual.Ver.zip)

@iku55 Thanks to you, I was able to finish it. Thank you.

**Comment by rubin110** [comment]
Why not submit this as a PR?

**Comment by 123JLaney123** [comment]
Just wanna say I really appreciate the work you both did here, thanks.

**Comment by 123JLaney123** [comment]
Hi, so I came across an issue when trying to launch the game via the tracker?
![1](https://user-images.githubusercontent.com/76238470/218187458-dc5b277d-a419-42b2-936c-113064caa00e.jpg)
![2](https://user-images.githubusercontent.com/76238470/218187572-7ffa6c39-bd1a-424f-a184-7349af9c1104.jpg)
![3](https://user-images.githubusercontent.com/76238470/218187588-9081abb8-8c38-4165-9e1b-14cb601208ba.jpg)

**Comment by qutrits** [comment]
@123JLaney123 I wasn't aware of this, but is it still possible to run fallguys through steam?

**Comment by 123JLaney123** [comment]
@qutrits It's always been possible to run through Steam, they just removed it from the Steam store when the game went free to play. You can still play it on Steam if you owned it and it works perfectly fine.
Then someone pointed out to me the ability to launch the game through the tracker got broken after the last update. Hence why I posted the above images.

**Comment by qutrits** [comment]
[FallGuysStats.zip](https://github.com/ShootMe/FallGuysStats/files/10715137/FallGuysStats.zip)

@123JLaney123 I don't have the steam version, so could you get it from the link above and test it to see if it runs well with steam?

**Comment by 123JLaney123** [comment]
@qutrits It worked when I clicked the "Launch Fall Guys" button but when I set it to auto-launch I got this 
![image](https://user-images.githubusercontent.com/76238470/218346272-c231c9c7-869f-445f-994e-28919f8f784d.png)

**Comment by 123JLaney123** [comment]
I just tried it again and it auto-launched fine.
