### ISSUE TITLE
[Suggestion] Add option in Level Stats to exclude Finish time (out for now, but qualified)

### ISSUE THREAD

**Issue by adamkelly86** [ShootMe/FallGuysStats#163]
There are a few times where a user may be eliminated from a round, but still finishes with a qualification and/or a win

This applies to any Duos and Squads show for the following round types: 

* Extreme Rounds (affixed with X eg Big Fans X)
* Survival Rounds (eg Sime Climb) 
* Finals where it's last one standing (eg Jump Showdown) 

Example attached below: 

![image](https://user-images.githubusercontent.com/37782715/215579848-4a8ccd7e-386f-4cdd-95d2-dbdec8bb75d5.png)

My suggestion is to offer a check box to exclude rounds where the tier is not set to Eliminated.

**Comment by iku55** [comment]
If you still have the log file, please upload it. If not, please upload the log file if you encounter this bug in the future.

Log path:
Steam: `%PROGRAMFILES(X86)%\Steam\steamapps\common\Fall Guys`
Epic: `%LOCALAPPDATA%Low\Mediatonic\FallGuys_client`
`Player.log`(last session) `Player-prev.log`(previous session)

**Comment by adamkelly86** [comment]
[Player - rhino.txt](https://github.com/ShootMe/FallGuysStats/files/10609917/Player.-.rhino.txt)

Show is Duos
Round is robotrampage
I was eliminated at 37.05 seconds, squad mate survived till the end.
