### ISSUE TITLE
Cant launch fall guys

### ISSUE THREAD

**Issue by ratesc** [ShootMe/FallGuysStats#171]
I was able to do it about two days ago, but now I can't start the game automatically when I start the launcher.
![image](https://user-images.githubusercontent.com/125166626/218288341-37c49f9b-2864-4a68-996a-e7bbd8d95ca0.png)
![image](https://user-images.githubusercontent.com/125166626/218288395-b725fe3c-20e8-43de-88b0-a4bcfe91846f.png)
I didn't change the setting
When I try to find a file with gameoptions, it searches in Korean for some reason. and file not found

It is possible to start the game and stats separately and monitor them
![image](https://user-images.githubusercontent.com/125166626/218288432-64e26745-d59b-413e-87ec-ea6e04c4925a.png)

**Comment by qutrits** [comment]
[FallGuysStats.zip](https://github.com/ShootMe/FallGuysStats/files/10715137/FallGuysStats.zip)

I don't have the steam version, so could you get it from the link above and test it to see if it runs well with steam?

**Comment by iku55** [comment]
@qutrits It looks like you were creating while I was creating. Which one do you use?
My fork fixes #171 (requires Korean and Chinese retranslation).

**Comment by qutrits** [comment]
@iku55 Does it work?
