### ISSUE TITLE
Tracker not working when putting old data.db file + Ghost 1.136 update

### ISSUE THREAD

**Issue by Taupe** [ShootMe/FallGuysStats#176]
Hello, 

I noticed that my old data.db file seems corrupted and the tracker doesn't launch until i move it to another folder and let the tracker create a new data file. All i have is this error :
![image](https://user-images.githubusercontent.com/81835593/218346222-2fc1bf9c-df1d-488f-976e-fdd0c00cb21b.png)

I also noticed that the tracker says that a 1.136 update is available, which causes the same error as above.

Could someone look into it ?

Thanks

**Comment by Taupe** [comment]
So downloaded that 1.136 version from this issue linked below :
https://github.com/ShootMe/FallGuysStats/issues/176
![image](https://user-images.githubusercontent.com/81835593/218347253-001aa0c4-dc48-469e-adab-eae1036c41af.png)

**Comment by Taupe** [comment]
l will actually leave the issue open just in case people with the same problem see this and until a fix is deployed 🙂

**Comment by qutrits** [comment]
[FallGuysStats.zip](https://github.com/ShootMe/FallGuysStats/files/10723365/FallGuysStats.zip)
