### ISSUE TITLE
Can't launch stats tracker

### ISSUE THREAD

**Issue by karateman10998** [ShootMe/FallGuysStats#184]
It keeps opening, crashing, reopening. When I did somehow have it open and running properly, it wasn't tracking show data at all

**Comment by iku55** [comment]
I have encountered the same issue.
FallGuysStats kept restarting until I ended it in task manager.
Also, the FallGuysStats icon was not displayed on the taskbar at that time.
Sorry for not being able to provide detailed information.

**Comment by Micdu70** [comment]
@iku55 I guess you enabled "Auto Update Program" option... :(
I will not explain why this option is broken but you can fix your problem by using the "ManualUpdate" version instead => https://raw.githubusercontent.com/ShootMe/FallGuysStats/master/FallGuyStatsManualUpdate.zip
