### ISSUE TITLE
Can't add Fall Guys Shortcut Location

### ISSUE THREAD

**Issue by Darshix** [ShootMe/FallGuysStats#188]
When I click to browse my files I can only see .url files, there's no option to even change that. It looks for "Fall Guys Clinet 바로가기" and I can't do anything about it. Please help me with this!! Thank you :)

**Comment by iku55** [comment]
This issue has been fixed, but a fixed version has not been released as zip.
so you can...
1. wait for ShootMe
2. build zip yourself
3. use [my build](https://github.com/ShootMe/FallGuysStats/files/10833992/FallGuysStats.188.zip)

**Comment by iku55** [comment]
@Darshix 
(If you're not using v1.136, build it yourself)
Epic Games:
1. Create shortcut of FallGuys
2. Select Epic Games in settings
3. Browse and select the shortcut
Steam:
1. Select Steam in settings
2. Browse and select exe file

**Comment by Darshix** [comment]
> @Darshix (If you're not using v1.136, build it yourself) Epic Games:
> 
> 1. Create shortcut of FallGuys
> 2. Select Epic Games in settings
> 3. Browse and select the shortcut
> 
> Steam:
> 
> 1. Select Steam in settings
> 2. Browse and select exe file

Thank you @iku55, your help is extremely valuable to me. Have a great rest of your day!
