### ISSUE TITLE
Unable to delete shows?

### ISSUE THREAD

**Issue by corbynj** [ShootMe/FallGuysStats#19]
I'm unable to delete shows from my stats when someone else was playing. I'm unable to select shows to delete, and right-clicking only gives an export menu. Either I'm doing something wrong, or the delete functionality was somehow removed. If I'm doing something wrong, would it be possible to make it more obvious how to delete shows?

**Comment by ShootMe** [comment]
Added info to the readme on the main page of the github. Let me know if that makes sense.

**Comment by corbynj** [comment]
Yep, that works. It was definitely user error. Thank you so much!
