### ISSUE TITLE
Can't update from v1.137 or older to v1.138/139

### ISSUE THREAD

**Issue by iku55** [ShootMe/FallGuysStats#196]
Unable to update with 404 Not Found error when trying to update from version 1.137 or older.
This is because FallGuyStats.zip was changed to FallGuy***s***Stats.zip when updating to v1.138.
(b20c2c3dd345cd07365697d72f1833347c1171e4 / bb69296788465f37e94b2dd6a8be1ea3ff93634c)
Would you like to upload FallGuyStats.zip for this issue?

P.S. I'm making a feature that releases updates automatically. What do you think about using [releases](https://docs.github.com/en/repositories/releasing-projects-on-github) for updates?

**Comment by qutrits** [comment]
Since it set the dll file to be embedded in the exe, it probably won't be a problem for this part anymore.

**Comment by iku55** [comment]
@qutrits I have a suggestion.
Wouldn't you like to use the release for updates?
[GitHub Docs: Releasing projects on GitHub](https://docs.github.com/en/repositories/releasing-projects-on-github)

When using releases the latest version of the files can be obtained at https://github.com/ShootMe/FallGuysStats/releases/latest/download/[filename].zip
Also you can check the latest version using API ( https://api.github.com/repos/ShootMe/FallGuysStats/releases/latest )

**Comment by qutrits** [comment]
Unfortunately, I don't have release permissions.
I hope @ShootMe sees this and gives me permission.

I'm going to spend some time reviewing and applying PRs.

**Comment by ShootMe** [comment]
You should have all permissions to the repo as far as I can see.
Navigate to this link and see if it allows you to do anything
https://github.com/ShootMe/FallGuysStats/releases

**Comment by qutrits** [comment]
@ShootMe I see that I can create a release, thank you.
