### ISSUE TITLE
Show time recorded wrong, Show start dates off

### ISSUE THREAD

**Issue by xShiller** [ShootMe/FallGuysStats#2]
So somehow, [this](https://i.imgur.com/fPWFkEf.png) occurred and I'm not sure when exactly. Looking at the individual Level Stats, their time is also weirdly affected by this. Also, start dates are wrong and I know my system date was correct during these times.
Is there a way to delete an individual show?

**Comment by ShootMe** [comment]
Very interesting, looks like it happened recently. If you haven't reopened the game since can you go to AppData/LocalLow/Mediatonic/Fallguys_client and attach the player.log and player-prev.log files? I can also fix the show for you or you can download LiteDB Explorer and modify the shows yourself in the data.db file

**Comment by xShiller** [comment]
I believe I have but I'll post them anyway, if you could that'd be great
[Player.zip](https://github.com/ShootMe/FallGuysStats/files/5158647/Player.zip)

**Comment by ShootMe** [comment]
Yea doesn't look like those logs had the issue. I tried to fix the logs, but it looks like there may have been some sort of other issues where it was reading things out of order, which makes me wonder if you had two instances of the stat program open at the same time?

Here is the updated file though
[data.zip](https://github.com/ShootMe/FallGuysStats/files/5158992/data.zip)

**Comment by xShiller** [comment]
You know, that might have happened but I don't think it was open for an entire show, just opened twice by accident. Thanks for the help.

**Comment by ShootMe** [comment]
Closing now since I believe this has been fixed since v1.30, and I haven't seen anyone getting weird results anymore.
