### ISSUE TITLE
1.140 update "resize overlay + show data"

### ISSUE THREAD

**Issue by SaYyIV** [ShootMe/FallGuysStats#200]
Hey. I downloaded the new update yesterday, but I have some questions. 

Q1:
How can I reduce the size of the overlay, because in the new update, it cannot be reduced more than before.

New Overlay :- 
![Capture1](https://user-images.githubusercontent.com/80646316/227792980-f9164e75-57d6-4992-949d-a89e4c783918.PNG)

Old Overlay :- 
![Capture2](https://user-images.githubusercontent.com/80646316/227792985-10683dad-45bb-494c-9cf7-1e849911f685.PNG)

Is there a new way to make the overlay smaller?

Q2:
I am trying to use my old data in my LiteDB.dll. It does not collect or read my previous data. Is there a way to add the previous data in the new version?

**Comment by qutrits** [comment]
A1:
Overlays have a minimum size and cannot be reduced any further. I will remove the minimum size and add the function to change the overlay to the default size via the Ctrl+Shift+D shortcut.

A2:
All dll files are embedded in the exe, so you don't need them anymore. Please delete all dll files from the folder. All your play data is stored in the data.db file, just make sure to keep the data.db file. Just put both the exe file and the data.db file in the same folder and run it.

**Comment by SaYyIV** [comment]
> A1: Overlays have a minimum size and cannot be reduced any further. I will remove the minimum size and add the function to change the overlay to the default size via the Ctrl+Shift+D shortcut.
> 

Thanks for the replay and I got my data from the data.db.

But the problem with the overlay, as you can see in the pictures, is covers most of the screen because Im using 175% windows display scale. It is preferable to put an option to reduce more

**Comment by SaYyIV** [comment]
Thank you for the fix now I can resize
