### ISSUE TITLE
System Argument Null Exception?

### ISSUE THREAD

**Issue by yeweivon** [ShootMe/FallGuysStats#208]
Not too sure what is happening right now. Whenever opening FallGuysStats, these warnings pop up on the screen. I tried both version, and both is having issue.
![1](https://user-images.githubusercontent.com/132220283/235366255-2e517313-b8e3-41ea-8555-84113b3e12ab.jpg)
![2](https://user-images.githubusercontent.com/132220283/235366256-10fa5bfc-0329-411d-9379-0f2c649f4ec8.png)

**Comment by qutrits** [comment]
Would you like to try v1.153?

**Comment by yeweivon** [comment]
> Would you like to try v1.153?

Tried, and the error is still happening.

**Comment by qutrits** [comment]
Download a fresh copy of the program from this link. Unzip the downloaded zip file, copy and paste the data.db file into the folder you were using before, and run it.
