### ISSUE TITLE
Backtracking saving can mess you up

### ISSUE THREAD

**Issue by kikifrh** [ShootMe/FallGuysStats#21]
I always play with the stats when I'm playing but today my girlfriend was playing (not even in the same steam account) with the program not running but after I switched back to my account and booted FallGuysStats it had saved Shows/Episodes she was playing on her account.

This would probably be a bigger problem in a house of siblings that share the pc but have multiple accounts, if it really works like this

**Comment by ShootMe** [comment]
Yea, the program reads from the games log file and if you are playing on the same computer it will all go in the same log directory. There isn't anything the program can do to differentiate different players. That is part of why Ive added the ability to delete shows. You can find info on that on the readme.

**Comment by kikifrh** [comment]
I see. If possible would be nice to save the data of which steam account played the epidose saved. If not I guess deleting can do the work. Thanks!
