### ISSUE TITLE
Support Season 4 FFA

### ISSUE THREAD

**Issue by iku55** [ShootMe/FallGuysStats#210]
Thanks for developing, contributors. The season 4 FFA is coming in May 10th.
According to official announcement of Fall Guys, the creative and 50 rounds (20 at launch) will be added.
Will you keep adding rounds to the table?
Also, do you think about creative rounds?

**Comment by qutrits** [comment]
The task is very simple.
 - Added 20 rounds that appear in solo shows

20 rounds are added, so we need to get round IDs for 20 rounds ASAP.

**Comment by iku55** [comment]
@qutrits Okay, I'll send you round list if I can get it.

**Comment by qutrits** [comment]
There are more rounds and shows than I thought, so if I don't get organized, I won't be able to update for a while.

**Comment by iku55** [comment]
Rounds List (All) [rounds.10.0.0.csv](https://github.com/ShootMe/FallGuysStats/files/11442434/rounds.10.0.0.csv)
Rounds List (Added in this season) [rounds.diff.csv](https://github.com/ShootMe/FallGuysStats/files/11442433/rounds.diff.csv)

UGC Rounds List (made using creative) [rounds_ugc_with_name.csv](https://github.com/ShootMe/FallGuysStats/files/11442432/rounds_ugc_with_name.csv)

Shows List (All) [shows.10.0.0.csv](https://github.com/ShootMe/FallGuysStats/files/11442435/shows.10.0.0.csv)
Shows List (Added in this season) [shows.diff.csv](https://github.com/ShootMe/FallGuysStats/files/11442431/shows.diff.csv)

Round ID of creative round is: ugc-\*\*\*\*-\*\*\*\*-\*\*\*\*
ex. ugc-8113-7002-5798

I added these data in #211 .
You should use the pr. Thank you.

**Comment by qutrits** [comment]
Currently, rounds played with shared codes are not saved. I've modified the timer so that it's still available, but I think I'm going to take a break for a while because I've used up too much energy.
