### ISSUE TITLE
[Bug]: sometimes the tracker overlay will make dwm go crazy

### ISSUE THREAD

**Issue by somerandostuff** [ShootMe/FallGuysStats#215]
### What happened?

(i think) it causes dwm to have a memory leak!!!

video:
https://github.com/ShootMe/FallGuysStats/assets/133385141/03bb7f19-fc5d-46f9-963d-8a45c72c2d15

(the same bug in question)
![image](https://github.com/ShootMe/FallGuysStats/assets/133385141/e80563a0-a70e-4368-99d9-6d52872e89b2)

edit: it doesn't happen with any other program except the tracker overlay

### Platform

Epic Games

**Comment by qutrits** [comment]
[Video](https://github.com/ShootMe/FallGuysStats/assets/4685412/eed628ad-c9f8-4c8d-91d0-dd4ad360dbb9)

I'm not experiencing any memory leaks, but it could be a setting in Stats, so please check what options you have turned on.

**Comment by somerandostuff** [comment]
nope, i just downloaded the tracker from release page

**Comment by somerandostuff** [comment]
also it would randomly happen and i don't know how to replicate it consistently

i also tried decreasing cycle time but to no avail

**Comment by qutrits** [comment]
Can you try it with version 1.165?

**Comment by somerandostuff** [comment]
updated and nope the bug still persists

one thing though, 
![image](https://github.com/ShootMe/FallGuysStats/assets/133385141/a3033d21-fcc1-4cc9-98b4-b1847e0c2c7f)
i noticed that this "aligner menu" thing, after it disappears, then the dwm starts to go crazy either instantly or after a few seconds

dunno if that relates to the problem...

**Comment by qutrits** [comment]
Let us know what version of Windows you are using.
Also, make sure you have the latest updates.

**Comment by somerandostuff** [comment]
reporting in, build 22621.1778 with fall guys tracker version 1.175
the dwm bug is finally gone, LET'S G!
