### ISSUE TITLE
[Bug]: Thin Ice rounds are being counted as Wins in mid Finals Marathon LTM rounds

### ISSUE THREAD

**Issue by ExodiaRM** [ShootMe/FallGuysStats#217]
### What happened?

Like title says, successful Thin Ice rounds are being counted as Wins in mid Finals Marathon LTM rounds

Is the only round with this old behavior in the tracker

![image](https://github.com/ShootMe/FallGuysStats/assets/81378878/4c36a3de-cf11-4c87-9ec4-17c30b32cd4e)

### Platform

Epic Games Version

**Comment by qutrits** [comment]
Can you try it with version 1.165?

**Comment by ExodiaRM** [comment]
> Can you try it with version 1.165?

![image](https://github.com/ShootMe/FallGuysStats/assets/81378878/5a41e44d-d44b-4ff8-bece-b3501d2369f8)

fixed
