### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by bushy9k** [ShootMe/FallGuysStats#229]
### What is your request?

Please add the the default nameplate that you get the first time you play fall guys as a overlay

**Comment by bushy9k** [comment]
its called monarch btw

**Comment by qutrits** [comment]
Edit the image and upload it here.

[Banner_Monarch.zip](https://github.com/ShootMe/FallGuysStats/files/11711182/Banner_Monarch.zip)

**Comment by bushy9k** [comment]
![Banner_Monarch](https://github.com/ShootMe/FallGuysStats/assets/134023632/5300a76e-e3ae-41ca-91ef-2e2b05f4d5e4)

**Comment by bushy9k** [comment]
are you gonna add it in v1.192?

**Comment by qutrits** [comment]
Download the zip file I uploaded, edit the background.png and tab.png files as banner images, and upload again.

**Comment by bushy9k** [comment]
thx for adding it!
