### ISSUE TITLE
Overlay stats are not matching Filter stats

### ISSUE THREAD

**Issue by faumyian** [ShootMe/FallGuysStats#23]
The overlay stats are not matching the filtered stats.  Is this intended, am I missing something, or are there plans to fix it?

**Comment by ShootMe** [comment]
By default the only stats that will match filter on overlay is the Wins/Finals. You can change behavior in the settings

**Comment by faumyian** [comment]
Understood. I overlooked that part of the settings. Thank you for clarifying!
![image](https://user-images.githubusercontent.com/71907271/94322791-0ccaa200-ff59-11ea-9863-5883b84aeab5.png)
