### ISSUE TITLE
[Question]: Where did overlay go?

### ISSUE THREAD

**Issue by DrPrufr0ck** [ShootMe/FallGuysStats#231]
I was messing around with the overlay and clicked the button on it to bind it to top-right of screen. Now, it has disappeared and nothing can bring it back (I tried every biding button and they worked without this issue). I can see it if I alt+tab and look at all open windows, and my OBS is also picking it up and I can see it there; however, I can't seem to actually get it back on my desktop.

I have tried hiding/showing overlay, changing display settings, restarting PC, and a few other things with no luck. Any suggestions?

**Comment by qutrits** [comment]
Do you mean the overlay's locations are set off-screen?

**Comment by DrPrufr0ck** [comment]
It seems as if the location is set somewhere off-screen. I have two monitors and I cannot find it even when I minimize everything else; however, I can see the overlay if I hold alt+tab and show all my open programs and my OBS is still finding it and displaying it on stream.

[FallGuysStats.zip](https://github.com/ShootMe/FallGuysStats/files/11713417/FallGuysStats.zip)

**Comment by qutrits** [comment]
Download the zip, unzip it and overwrite the FallGuysStats folder you are using.
Then run it and press Ctrl+Shift+C.

[FallGuysStats.zip](https://github.com/ShootMe/FallGuysStats/files/11713420/FallGuysStats.zip)

**Comment by DrPrufr0ck** [comment]
Yep, that did the trick. Thank you!
