### ISSUE TITLE
[Question]: Can you not drag the overlay anymore?

### ISSUE THREAD

**Issue by rafaelgomesxyz** [ShootMe/FallGuysStats#232]
### What is your question?

I used to be able to drag the overlay around, which was super helpful, but ever since one of the recent updates (I don't know which one) I can't seem to be able to do that anymore. On top of that, it also appears that I can't move it to my second monitor, where I like to keep it, which is incredibly annoying.

**Comment by qutrits** [comment]
Make sure the menu to pin the overlay is turned on.

![screenshot](https://github.com/ShootMe/FallGuysStats/assets/4685412/8e9e014c-ac09-44a7-b785-b656c76d8c57)

**Comment by rafaelgomesxyz** [comment]
Ah, mine was stuck in a corner, so I couldn't see any pin menu and I didn't know that I had to click on the selected corner again to restore it. I feel like the UI could be improved as it's not very intuitive, but my issue is solved, thanks!
