### ISSUE TITLE
[Bug]: I still have 2 different gamerules of Leading Light that were used in SS2

### ISSUE THREAD

**Issue by Taupe** [ShootMe/FallGuysStats#233]
### What happened?

![image](https://github.com/ShootMe/FallGuysStats/assets/81835593/6afa215b-0977-4902-ba00-913193fc786f)

Self explanatory. I'm apparently the only one with this too.

### Platform

Epic Games

**Comment by qutrits** [comment]
[Email](terro21c@gmail.com) me the data.db file.

**Comment by Taupe** [comment]
File is too big. Add me on Discord : taupe. / Taupe#0069 so i can share it to you

**Comment by qutrits** [comment]
Upload the file [here](https://gofile.io/welcome) and email me the link.

**Comment by iku55** [comment]
@qutrits They're probably this round id. Could you add this to `UpdateDatabaseVersion`?
- round_follow-the-leader_ss2_launch
- round_follow-the-leader_ss2_parrot

**Comment by Taupe** [comment]
Fixed now
