### ISSUE TITLE
[Bug]: System.NullReference LogFileWatcher can't find references

### ISSUE THREAD

**Issue by Antoine2a** [ShootMe/FallGuysStats#235]
### What happened?

Hello got a System.NullReference error playing fallguys with tracker today (15/06/2023)

Deleted my tracker and downloaded the latest version (v1.195) and same error occured :

![image](https://github.com/ShootMe/FallGuysStats/assets/39760350/9499a744-5a97-4c5f-8e7c-daf81abae0ed)

Looking into my Fall Guys files : D:\SteamLibrary\steamapps\common\Fall Guys : can't found Player.log file =/
I have no idea if it's linked
![image](https://github.com/ShootMe/FallGuysStats/assets/39760350/a5e494c3-5232-4535-9878-8475fcc66534)

It doesn't looks like a data.db error but I can upload if it is required.

### Platform

Steam

**Comment by Antoine2a** [comment]
Looks like a Steam Update and Playing Solo Show fixes the bug (player.log might have reset and I have no more the problem)
Can't reproduce the bug atm; I'll let you know if the bug comes up again otherwise issue can be closed

**Comment by iku55** [comment]
Sorry, I made a mistake when I made issue templates. Correct log location is `%LOCALAPPDATA%Low\Mediatonic\FallGuys_client`.

**Comment by Antoine2a** [comment]
Managed to find the player log file thanks you !
And as I said , I have no longer the bug; i'll reopen an issue if something wrong happen. Thanks for helping me 😁

> Looks like a Steam Update and Playing Solo Show fixes the bug (player.log might have reset and I have no more the problem)
Can't reproduce the bug atm; I'll let you know if the bug comes up again otherwise issue can be closed
