### ISSUE TITLE
[Bug]: Right Clock Context Menu for taskbar icon appears in wrong location for certain users...

### ISSUE THREAD

**Issue by ApacheThunder** [ShootMe/FallGuysStats#239]
There is a UI bug appears in one of the recent updates to this app (not related to the game). The right click context menu for the taskbar icon appears at the bottom of the screen despite the fact I have the taskbar at the top of the screen. Currently on Windows 10 Pro. Sure I'm probably in a minority of users who have the taskbar setup like this, but hard-coding the context menu seems like a bad idea (assuming that is what happened here)

Only app I've come across in all my years that is doing this....I'm not even sure how you managed to pull that off.  Some ill decided Windows 11 thing? I seem to recall Windows 11 taskbar can't be moved like in Win10 and older OS. But I don't use that OS so I wouldn't know. :P

### Platform

Steam

**Comment by qutrits** [comment]
Could you check it out in version 1.205?

**Comment by ApacheThunder** [comment]
Ok updated just now and confirmed bug appears to be resolved. :D
