### ISSUE TITLE
[Bug]: Win tracker is counting each round in Hex-a-thon as a win (again)

### ISSUE THREAD

**Issue by ApacheThunder** [ShootMe/FallGuysStats#240]
### What happened?

The bug with it counting each round in Hex-a-Thon as a win on the win counter has returned as of version 1.219. Yesterday it had not been doing this but after the app updated this morning that issue has returned.

### Platform

Steam

**Comment by qutrits** [comment]
Fixed in version 1.220. Thank you.

**Comment by ApacheThunder** [comment]
Cool. I'll close this for now and reopen if I encounter it again. :D
