### ISSUE TITLE
[Question]:  Overlay position + size problem

### ISSUE THREAD

**Issue by LummaDesign** [ShootMe/FallGuysStats#244]
### What is your question?

Since the new update I notice that the position & size of the overlay always resets / moves automatically than what I have chosen myself.

So I have to manually move this again and again and set the size of the overlay correctly.

i added a link to a video on streamable

[https://streamable.com/yf3bqv](url)

regards

**Comment by qutrits** [comment]
Check it out in version 1.231

**Comment by ApacheThunder** [comment]
Aaand it's back. Today's update brought the issue back for me. :(
