### ISSUE TITLE
[Feature Request]: Keyboard shortcut to hide/show the overlay

### ISSUE THREAD

**Issue by cesarravenclaw** [ShootMe/FallGuysStats#245]
### What is your request?

Keyboard shortcut to hide/show the overlay.

And keep doing the great job :)

**Comment by qutrits** [comment]
There is no indication, but if you click the main window and press Ctrl+O, it works. In the next update, i plan to make it work even when the overlay is focused.

**Comment by cesarravenclaw** [comment]
Just now I have seen it, thanks for the solution.
