### ISSUE TITLE
[Question]: sorry how to remove this error?

### ISSUE THREAD

**Issue by keroberos-s** [ShootMe/FallGuysStats#247]
### What is your question?

What is this?
![idont](https://github.com/ShootMe/FallGuysStats/assets/71687755/4ff19515-661a-4883-b924-f70b62e5f8fc)

**Comment by qutrits** [comment]
Did you run it on Linux?

**Comment by keroberos-s** [comment]
no i am using window 10.......

**Comment by qutrits** [comment]
Did you follow [this procedure](https://github.com/ShootMe/FallGuysStats#how-to-set-launch-fallguys-option-in-epic-games)?

**Comment by keroberos-s** [comment]
yes

**Comment by qutrits** [comment]
Try it on version 1.234.

**Comment by keroberos-s** [comment]
![f](https://github.com/ShootMe/FallGuysStats/assets/71687755/459009e5-f508-4784-ad18-7c198cc56a71)

**Comment by qutrits** [comment]
Do you not have Steam installed on your PC?

**Comment by qutrits** [comment]
Try it on version 1.235.

**Comment by keroberos-s** [comment]
I cannot try today sry!   will try tomorrow
