### ISSUE TITLE
[Bug]: The .exe is running on background but the GUI dont open

### ISSUE THREAD

**Issue by cesarravenclaw** [ShootMe/FallGuysStats#250]
### What happened?

When I open the FallGuysStats.exe (with or w/o the admin rights) the GUI or the tray icon just dont show up. The .exe is running on taskmanager but nothing else happens. 

If i delete my data.db file its run normally, but when I put it back it dont. So its provably some error in my file.
There's any way to fix that without losing all my stats?

Thanks in advance.

[data.zip](https://github.com/ShootMe/FallGuysStats/files/12413615/data.zip)

### Platform

Epic Games

**Comment by qutrits** [comment]
Try running [this](https://github.com/ShootMe/FallGuysStats/files/12414601/data_modified.zip) one more time.

**Comment by cesarravenclaw** [comment]
Yeah, its working now thanks for the help.
Just in case it happens with someone else, to fix it now i had to replace the file but also delete the log.db file (this didn't worked before).
And I think it bugged when I disabled the option "Use system tray icon" a few versions ago.

Thanks again and keep doing your great work.
