### ISSUE TITLE
[Bug]: 1.253 NullReferenceException on startup (eventual crash?)

### ISSUE THREAD

**Issue by realrellek** [ShootMe/FallGuysStats#251]
### What happened?

Hi,

today's update is starting up with a NullReferenceException, works for a moment regardless and eventually quits. Looks like the quit happens when a game ends (in my case, I got eliminated).
(Edit: Hmm I tried to reproduce and it didn't crash this time at least, so maybe it was coincidence and unrelated)

![Screenshot 2023-08-23 063143](https://github.com/ShootMe/FallGuysStats/assets/91732532/d5ba356a-ea48-480c-a0cd-205d62c008b3)

### Platform

Steam

**Comment by qutrits** [comment]
Update to version 1.254 and try it.

**Comment by realrellek** [comment]
Thank you, error on startup is gone. (And crash did not happen after that first time, so I guess it isn't a real problem)

Thanks again :)
