### ISSUE TITLE
Binary release files shouldn't be part of the repo

### ISSUE THREAD

**Issue by omega32** [ShootMe/FallGuysStats#252]
### The issue
Hi, I love this app, use it all the time, and I'm thankful for all the effort the creator and the community has put into it.

I would love to contribute to the project but there's one thing giving me some pause. If you clone the main branch, the repo will weight more than 7GB (almost 8 at the moment of writing) (and rapidly growing).

Caused by including the compiled binary with the code, it's growing about **40+MB** each release.

I don't know the rationale behind including the binary this way, but it's not common for a project to do that.

### Potential fix | use the release attached files
If this is being done to facilitate the auto-update feature of the app, I don't think there's an actual need for including the binary like that. You could just access the latest release using the **`latest`** tag. For example:
[https://github.com/ShootMe/FallGuysStats/releases/latest/download/FallGuysStats.zip](https://github.com/ShootMe/FallGuysStats/releases/latest/download/FallGuysStats.zip)

You can even have other tags, for beta releases, etc. Some projects have a text file with links to different releases and validate those client side.

### Benefits of committing binary builds to the repo?
I don't see any benefit to having it as a version-controlled file inside the actual code branch. But I'm open to hearing them.

If for some reason you need to have them in the repo, you could create a branch with the sole purpose of having this binary files. And never merge it back to main/master. Then developers could clone the main/master branch without downloading GBs of previous binary release files.

**PD**: I see there are 4 .zip files (2 different binaries but 4 .zip files). I don't know why, but I'm sure there is a solution without having to constantly commit those to master.

**Comment by qutrits** [comment]
Delete the existing repository and try cloning again.
