### ISSUE TITLE
[Bug]: pink medals 

### ISSUE THREAD

**Issue by otherbeanmore** [ShootMe/FallGuysStats#262]
### What happened?

For a few days now, I have observed that the program does not detect the medals (Squads, solos, duo, extreme), and detects some finals as lost, (hex a gone in image)  I put a screenshot
![Captura de pantalla 2023-10-17 013717](https://github.com/ShootMe/FallGuysStats/assets/148195978/8337dac5-7a87-4a90-b83d-49ef501c552d)

### Platform

Epic Games

**Comment by omega32** [comment]
Thanks. This is related to the issue #261 
I think the best thing we can do right now is go back to a previews version and stop updating for the time being.
I'll try and identify the last version that was working correctly and post it here.

**Comment by omega32** [comment]
Downgraded to version v1.274 and it seems to be working correctly, at least in this regard. Haven't tried 1.275 yet.

I'm having other issues but they are on older version as well.

**Comment by qutrits** [comment]
Try it in v1.278

**Comment by omega32** [comment]
> Try it in v1.278

Yes, medals and wins appear to be working again 👍‍‍

**Comment by otherbeanmore** [comment]
I will check more later that version, (I'm not at home right now) I'm not at home right now)

**Comment by otherbeanmore** [comment]
Fixed thanks UwU
