### ISSUE TITLE
Suggestions for the overlay field which shows WIN!/FAILURE!

### ISSUE THREAD

**Issue by FallGuysStatsStan** [ShootMe/FallGuysStats#265]
### What is your request?

I have a few suggestions for the part of the overlay which displays the finish time. This currently has a feature which adds the text WIN! or FAILURE! in front of the finish time at the end of a game. 

For my own use cases, I don't find this WIN/FAILURE feature useful: I already know if I won the game so the information isn't telling me an interesting statistic; and the tracker cannot know what the player's objectives were when playing the game in order to report success/failure reliably. For example, if the objective is to complete the daily challenge to play Custom Shows, a game can be successful without surviving or coming first.

Suggestion 1: have a toggle for this feature in the overlay settings, similar to the 'hide percentages' toggle
Suggestion 2: change 'FAILURE!' to 'LOSS!', as this word is shorter/easier to fit in the space and is grammatically more accurate as the opposite of WIN
Suggestion 3: potentially a bug, but the text color of the WIN/FAILURE message is inconsistent - sometimes it shows WIN in red, sometimes in white, sometimes in green. The colored text is distracting so it could be left in white throughout.

![FGST suggestion for the Win field in the overlay](https://github.com/ShootMe/FallGuysStats/assets/140942221/8d26bb70-c5aa-474e-a040-8dc07fa6502b)

**Comment by keroberos-s** [comment]
just how about `fail?`

**Comment by FallGuysStatsStan** [comment]
> just how about `fail?`

It is shorter, but has a similar problem to `failure` grammatically (not the right word in English) and logically (fail state can't be evaluated reliably)

**Comment by FallGuysStatsStan** [comment]
Hurrah, this is now addressed with the checkbox option under `Settings > Overlay > Display game played information at the end of a round (Rank, Survived, Win, etc.)`
Thank you!
