### ISSUE TITLE
[Feature Request]: Don't count rounds exited early as eliminations (or make it a setting users can toggle)

### ISSUE THREAD

**Issue by knightry** [ShootMe/FallGuysStats#268]
### What is your request?

There was some change recently where if you leave a round early for any reason it gets added as a loss in the tracker. I play in parties a lot where someone frequently will get disconnected and everyone will leave the round to requeue, and having these count in the tracker as losses doesn't really make sense.

I get the rationale why some would like to consider these rounds as losses, so at the very least I'd like to request it be made a setting where we can choose whether to count them as "full" rounds or not.

Thanks!

**Comment by RenJay7** [comment]
agree

**Comment by omega32** [comment]
100% agreed, or give us the option to choose. Sometimes you need to back out for whatever reason (a teammate disconnected for example) but you don't wanna loose your win streak.

**Comment by qutrits** [comment]
![image](https://github.com/ShootMe/FallGuysStats/assets/4685412/6cd01de8-81ec-4cb4-98bf-324928b692da)

**Comment by omega32** [comment]
awesome! thanks 🙂
