### ISSUE TITLE
Problem with nulls (Profile without name)

### ISSUE THREAD

**Issue by TheCarlitosYT** [ShootMe/FallGuysStats#269]
A while ago when you updated and added profiles to this tracker, by mistake I skipped the step to indicate the name, so I am using the program with a profile without a name, with all the stats, this profile detects it as null. I tried to change the name or move the data but it is impossible (since it is null, it cannot be selected and more errors occur), It was not the intention to leave it nameless. 
The first versions only appeared a few errors and worked well, so I didn't give it much thought. But with these latest updates, it is very difficult to start the application or when playing certain rounds another error occurs, making it impossible to play with the tracker. 
Is there a way to fix it? I don't want to modify anything internal by mistake or lose all my data (+1.5 year of data).

**Comment by qutrits** [comment]
Try it in v1.289.

**Comment by TheCarlitosYT** [comment]
> Try it in v1.289.
Thanks for the quick response, I tried updating the tracker and when I try to run it, another error appears and it won't let me use it directly.

**Comment by qutrits** [comment]
Send me your data.db file.

**Comment by TheCarlitosYT** [comment]
> Send me your data.db file. You can email([terro21c@gmail.com](mailto:terro21c@gmail.com)) it to me or upload it here.


Hello! Sorry for the delay, I already sent you the email via gmail. Thank You!

**Comment by qutrits** [comment]
Try adjusting the overlay transparency and changing the filter to all.

**Comment by TheCarlitosYT** [comment]
Already works, thank you very much for fixing it :)
Only one very curious thing happens, the statistics are shown in the overlay but not in the application.

![image](https://github.com/ShootMe/FallGuysStats/assets/72863936/a1ac3c1e-3cc7-4b5a-a26c-b4f6a7ebb276)

**Comment by qutrits** [comment]
Change it to All in the Filters menu at the top.

**Comment by TheCarlitosYT** [comment]
Oh, I didn't notice that the filters were in custom, my mistake, THANK YOU very much for solving it, it now works perfectly. I'm really grateful.
