### ISSUE TITLE
[Bug]: Updater dialog is sometimes invisible

### ISSUE THREAD

**Issue by aaronliu0130** [ShootMe/FallGuysStats#270]
### What happened?

Since a few days ago, after the "Run fall guys" window pops up and I do something, what should be the update dialog might have started but the entire window is invisible, at least in the task switcher as I cannot find it anywhere. Pressing spacebar enables you to select. I have a 4k monitor, 125% scaling and Rectify11 if that is of any relevance.

### Platform

Steam

**Comment by qutrits** [comment]
I don't understand exactly what you mean, could you please explain?

**Comment by aaronliu0130** [comment]
This has now been fixed by only requesting to launch when the full thing has been loaded, i.e. after the updater dialog.
