### ISSUE TITLE
[Bug]: Non stop windows notifications

### ISSUE THREAD

**Issue by karateman10998** [ShootMe/FallGuysStats#273]
### What happened?

I got a new PB and now I'm getting non stop notifications popping up on the bottom right of my screen. Please add an option to turn these off entirely. They are so annoying

### Platform

None

**Comment by qutrits** [comment]
Try it on v1.292 and let me know if it happens again.

**Comment by karateman10998** [comment]
it no longer endlessly notifies on 1.292 but I still would like an option to turn them off entirely
