### ISSUE TITLE
[Bug]: only the overlay is displayed

### ISSUE THREAD

**Issue by AymericKing** [ShootMe/FallGuysStats#275]
### What happened?

When I click FallGuysStats.exe to launch it, only the overlay is displayed from the last update and there is no way to display the tracker menu. In addition, the message if I want to launch my game is also shifted to the left on my PC

### Platform

Epic Games

**Comment by qutrits** [comment]
Do you use wallpaper engine?

**Comment by AymericKing** [comment]
> Do you use wallpaper engine?

What do you mean Wallpaper engine?

**Comment by qutrits** [comment]
You need to explain the situation in detail so I can understand.

**Comment by AymericKing** [comment]
> You need to explain the situation in detail so I can understand.

When I launch fall guys tracker, only the overlay is displayed and even by clicking on this software at the bottom, it considers that it is currently running

**Comment by AymericKing** [comment]
Up?

**Comment by AymericKing** [comment]
The file that would prevent the tracker menu from being displayed is data.db for some reason does not display it. someone would explain why i have this issue please
