### ISSUE TITLE
[Bug]: Error network, Non-stop errors after qual, non-stop noficitations 

### ISSUE THREAD

**Issue by repinek** [ShootMe/FallGuysStats#277]
### What happened?

A bug happened! After qual i get error, after i updated programm to 1.926 i click update and get network error and non-stop nofications
![image](https://github.com/ShootMe/FallGuysStats/assets/137826826/9fe8c731-2f4f-46d9-b776-244e2972a663)
![Screenshot_3131](https://github.com/ShootMe/FallGuysStats/assets/137826826/eeda7b9b-21d0-4a8c-98df-83a710ccd638)

### Platform

Steam

**Comment by repinek** [comment]
[Player.log](https://github.com/ShootMe/FallGuysStats/files/13297096/Player.log)

**Comment by qutrits** [comment]
[FallGuysStats.zip](https://github.com/ShootMe/FallGuysStats/files/13302925/FallGuysStats.zip)
Could you please try this file and let me know if you still see problems? Thank you for your help in fixing the bug.

**Comment by repinek** [comment]
ok thank
