### ISSUE TITLE
[Bug]: Incorrect name of show in notification

### ISSUE THREAD

**Issue by repinek** [ShootMe/FallGuysStats#278]
### What happened?

I playing day at the races of squads 
![Screenshot_3133](https://github.com/ShootMe/FallGuysStats/assets/137826826/e3339c65-c100-44b0-90e2-57d322a567f3)

### Platform

Steam

**Comment by repinek** [comment]
im on 1.297
[Player.log](https://github.com/ShootMe/FallGuysStats/files/13309485/Player.log)

**Comment by repinek** [comment]
![Screenshot_3134](https://github.com/ShootMe/FallGuysStats/assets/137826826/4383a1bd-d985-4f11-b49d-3131991eef9b)

**Comment by Micdu70** [comment]
Fixed in v1.305.
