### ISSUE TITLE
[Bug]: Run Exception (System.Exception: LiteDB ENSURE: get only index below highest index...)

### ISSUE THREAD

**Issue by FallGuysStatsStan** [ShootMe/FallGuysStats#279]
### What happened?

Fall Guys Stats v1.297 was running alongside Fall Guys. Fall Guys Stats started producing a continuous series of 'red box' errors (not screen capped) until I closed it from the system tray. I then closed both Fall Guys and Fall Guys Stats, restarted the PC and attempted to relaunch Fall Guys Stats. Now, whenever I try to launch Fall Guys Stats it gives the error message below and does not launch.

I have tried rolling back to earlier releases by replacing FallGuysStats.exe with v1.296 and v1.290 but the same error occurs with slightly different Stats.cs line references. If I remove my latest data.db file the program is able to launch successfully and generate a new data.db and import data (from Player.log / Player-prev.log). Therefore, the issue may relate to the data.db file and I have attached a copy of this.

Thank you for any help with this!

![image](https://github.com/ShootMe/FallGuysStats/assets/140942221/72cd3648-1c9c-4bfd-ae49-03b97041fe44)

[data.zip](https://github.com/ShootMe/FallGuysStats/files/13313698/data.zip)

### Platform

Epic Games

**Comment by Micdu70** [comment]
"fixed" database here: [data.zip](https://github.com/ShootMe/FallGuysStats/files/13317436/data.zip)

**Comment by FallGuysStatsStan** [comment]
Thank you so much, this is now working
