### ISSUE TITLE
[Bug]: non stop errors when open programm 

### ISSUE THREAD

**Issue by repinek** [ShootMe/FallGuysStats#280]
### What happened?

![image](https://github.com/ShootMe/FallGuysStats/assets/137826826/28498722-805c-4c34-9cf9-446166268ef8)
if i click ok the error will happen again

### Platform

Steam

**Comment by repinek** [comment]
[Player.log](https://github.com/ShootMe/FallGuysStats/files/13325786/Player.log)
data.db can send on email

**Comment by Micdu70** [comment]
Please send "Player-prev.log" too when reporting issue (but maybe it's too late now...)

**Comment by repinek** [comment]
> Please send "Player-prev.log" too when reporting issue (but maybe it's too late now...)

sorry, too late, im already restarted fall guys a few times and tracked works normally
