### ISSUE TITLE
[Bug]: Issues on the Steam name of the leaderboard

### ISSUE THREAD

**Issue by RainbowStays** [ShootMe/FallGuysStats#285]
### What happened?

(1) For users with multiple Steam accounts, the name on the leaderboard always corresponds to the earliest logged-in local Steam account, regardless of whether that account has Fall Guys or not, rather than the latest one.
(2) If you delete the relevant account, the leaderboard name will change to the second earliest account. Your previous records uploaded to the leaderboard will be retained, which means that if you break your records again, the new records might appear duplicated.、
Can we choose the steam profile we want to display, or we can choose to set up a unique name inside the stats? Thanks!

### Platform

Steam

**Comment by qutrits** [comment]
Can you send me the loginusers.vdf file in the config folder of the Steam installation folder by email? (terro21c@gmail.com)

**Comment by RainbowStays** [comment]
> Can you send me the loginusers.vdf file in the config folder of the Steam installation folder by email? ([terro21c@gmail.com](mailto:terro21c@gmail.com))

Sure

**Comment by qutrits** [comment]
Try it in v1.305.

**Comment by RainbowStays** [comment]
After the update I cannot have my records uploaded any more.
For example I got new PBs in Treetop Tumble and a UGC level in the show tab, but there isn't any records on the leaderboard.
![image](https://github.com/ShootMe/FallGuysStats/assets/46221436/9f124f32-2e07-4941-902c-a14cdc2388ef)
![image](https://github.com/ShootMe/FallGuysStats/assets/46221436/a10e5ad7-8580-42fa-b5b6-73edd271f412)
I checked my settings and it's fine.

Also I noticed that the stats won't recognize me as tianbaba and RainbowStays RU any longer, which were mine previously. It's kind of strange.
![image](https://github.com/ShootMe/FallGuysStats/assets/46221436/52dadfe8-7ebc-44ed-9c1a-bed44484d58d)

**Comment by qutrits** [comment]
Please email me your data.db file. (terro21c@gmail.com)

**Comment by RainbowStays** [comment]
I have sent the email earlier, and today I backuped and deleted my old db file and try to start a new profile, but I'm still not be able to submit to the leaderboard even if I broke records many times for many levels. One of my friends has the same issue. Maybe the problem it's not related to the data.db file.

**Comment by qutrits** [comment]
I haven't received any emails.

**Comment by RainbowStays** [comment]
I sent another email attached with the old and new data.db file. Let me know if you don't receive any email.

**Comment by qutrits** [comment]
I'm still not receiving any emails. Please check again.

**Comment by qutrits** [comment]
Try it in v1.309.
For records already registered, manual deletion is required.

**Comment by RainbowStays** [comment]
Fixed. Thanks!
