### ISSUE TITLE
[Feature Request]: Support opening already running instance on relaunch

### ISSUE THREAD

**Issue by jonbloom** [ShootMe/FallGuysStats#286]
### What is your request?

When you have the tracker running in the system tray, it's easy to forget it's in the background. Launching the tracker from the start menu when the tracker is already running triggers an error message. Instead, could it reopen the GUI of the existing instance?

**Comment by qutrits** [comment]
Try it in v1.307.

**Comment by jonbloom** [comment]
Amazing. Thank you so much for your hard work on this application!
