### ISSUE TITLE
Overlay is squashed vertically.

### ISSUE THREAD

**Issue by Confuzzaluzzle** [ShootMe/FallGuysStats#29]
I updated a couple days ago and since then the overlay is the same length but the height is smaller so its squashed. I redownloaded the files and that one was fine so I copied over the data.db file to get all my play data in then that one becomes squashed aswell. When I delete the data file it goes back to normal.
With data file: ![image](https://user-images.githubusercontent.com/16371382/95066848-ddefc100-06fa-11eb-9ab1-946f8038d93f.png)
Without data file: ![image](https://user-images.githubusercontent.com/16371382/95066925-f8299f00-06fa-11eb-9bdb-b4998edfbc53.png)

**Comment by ShootMe** [comment]
This came about from the new feature of being able to manually resize the overlay on the corners and having the show Tab option enabled. If you just want it to reset, then you can enable/disable any of the Hide options in the settings and then re-enable/disable it.
