### ISSUE TITLE
Missing Transparency on Overlay

### ISSUE THREAD

**Issue by teknogeek** [ShootMe/FallGuysStats#3]
There seems to be a bug where the stats overlay is not transparent, and instead, it renders the corner as solid pink:

![](https://i.imgur.com/rawRQc1.png)

This is on v1.32 compiled from src

**Comment by ShootMe** [comment]
There is already a feature for this you hit 'T' to toggle through different background colors, and Transparent is one of them.
The magenta/pink is for stream overlays to chroma key out.

**Comment by kowzzz** [comment]
Thanks for doing all of this and this project. It is pretty awesome. Would you mind putting that info in the read me? I wasn't aware of this function, and I am sure there are others I am unaware of.

**Comment by ShootMe** [comment]
Thanks, and yea I plan to do that. Just been a lot of additions recently and haven't got to documentation yet :)
