### ISSUE TITLE
[Bug]: Fall Ball incorrectly counting as final in Classic Knockout

### ISSUE THREAD

**Issue by lunareclipse777** [ShootMe/FallGuysStats#303]
### What happened?

![Screenshot 2023-12-08 161543](https://github.com/ShootMe/FallGuysStats/assets/140643890/7d3f178d-8d0f-49e9-9494-dedbe73dc95f)
The tracker counts Fall Ball (and Jinxed also) as a final, even though it´s a regular round

### Platform

Epic Games

**Comment by qutrits** [comment]
Try it in v1.314.
