### ISSUE TITLE
[Bug]: submit record error

### ISSUE THREAD

**Issue by adsczxi** [ShootMe/FallGuysStats#306]
### I can't submit record to Fallalytics
maybe this is an archiving issue
I made the mistake of recording the dous results in the squads
then,I won't be able to see this record in ranking list
<br>

[![20231209-003835.png](https://i.postimg.cc/jqmktL93/20231209-003835.png)](https://postimg.cc/G9Pjjhbv)
[![da430d44-e6e6-4521-b576-4c5ac9ddad88.jpg](https://i.postimg.cc/25HNwC6p/da430d44-e6e6-4521-b576-4c5ac9ddad88.jpg)](https://postimg.cc/HJ7NWDX3)
[![image.png](https://i.postimg.cc/L8s6zQ9b/image.png)](https://postimg.cc/PPBjH48W)

**I would be grateful if you could help me!!**

### Platform

Epic Games

**Comment by qutrits** [comment]
We're not looking for the best of all the user's records, we're looking for the best of the records that contain the session ID and show ID to register the PB. Stats started storing session IDs and show IDs about 6 months ago.

You can add your existing record to the leaderboard once, and after that, the leaderboard will be updated every time you beat your leaderboarded PB.

**Comment by adsczxi** [comment]
I have added outdated records but now they are not updated
how can i do?

**Comment by qutrits** [comment]
Email your data.db file. (terro21c@gmail.com)

**Comment by qutrits** [comment]
Did you run stats after the show was over?

**Comment by adsczxi** [comment]
I run stats when I played fall guys and it shows broke pb

**Comment by adsczxi** [comment]
I guess it's because I logged the dous results into squads

**Comment by adsczxi** [comment]
can u understand what I mean, I am not good at English😂

**Comment by qutrits** [comment]
The current logic prevents users from registering PBs if they run Stats after the show ends.
this will be fixed and the data.db file will be sent after the fix.

**Comment by adsczxi** [comment]
but I never turn off stats

**Comment by adsczxi** [comment]
can u add a manual retry mechanism where the commit operation is not transparent to the user

**Comment by adsczxi** [comment]
maybe it cannot be uploaded to Fallalytics due to GFW
