### ISSUE TITLE
[Feature Request]: Add a mode of LTM

### ISSUE THREAD

**Issue by EnoGaming29** [ShootMe/FallGuysStats#320]
### What is your request?

Hello, I have seen that a mode is missing on the tracker. In effect, the last week, the LTM "Lily Leapers Limbo" (*Fol'Virevoltes Tropicales in French*) was appearing but, the tracker didn't recognize it. Can you add it to allow the tracker to choose it when we play at this mode.
Thanks for reading my message and have a good day :) .
Kind Regards, EnoGame

**Comment by Micdu70** [comment]
Will be added in v1.319 (upcoming release)

**Comment by EnoGaming29** [comment]
Ok, thank you for your answer <3 . I will wait for this version so 😅.
