### ISSUE TITLE
[Bug]: Behavior becomes strange when the show number exceeds 1000

### ISSUE THREAD

**Issue by ohsakura0** [ShootMe/FallGuysStats#323]
### What happened?

Behavior becomes strange when the show number exceeds 1000.
Is there anything I can do without deleting the data?

(Sorry,Translations used and may be inaccurate)

![image](https://github.com/ShootMe/FallGuysStats/assets/127501702/609a743e-614c-4db0-aa0a-a87f0502da1e)

### Platform

Epic Games

**Comment by qutrits** [comment]
[Email](terro21c@gmail.com) me your data.db file.

**Comment by ohsakura0** [comment]
Is this alright?

[data.zip](https://github.com/ShootMe/FallGuysStats/files/14077451/data.zip)

**Comment by qutrits** [comment]
Try playing the game again and see if it still only saves the first round.

**Comment by ohsakura0** [comment]
Yes, it will happen

![image](https://github.com/ShootMe/FallGuysStats/assets/127501702/95a0bfcc-2e66-47ae-b901-0330e61d144f)

Normal:
![image](https://github.com/ShootMe/FallGuysStats/assets/127501702/9299ccc2-1e67-4763-9448-9ec113f94bdf)

Also, a popup like this will appear when ELIMINATED
![image](https://github.com/ShootMe/FallGuysStats/assets/127501702/e5f752dc-5884-4941-a84c-3d7bbc84d684)

**Comment by Micdu70** [comment]
Here's your "fixed" database (no bug/popup):

[fixed-data.zip](https://github.com/ShootMe/FallGuysStats/files/14091719/fixed-data.zip)

;)
