### ISSUE TITLE
[Bug]: Error occurs at startup and data cannot be loaded or saved

### ISSUE THREAD

**Issue by takkun-mint** [ShootMe/FallGuysStats#325]
### What happened?

A bug happened!

When I start Stats, I get the error in (1). (It appears twice in a row.)
The program automatically becomes resident and the main screen is not displayed.
For some reason, the overlay is also not displayed, and when I display it from the resident part, the font has changed, and the last round played is also displayed as "N/A" and it looks as if the data has disappeared (2).
When I try to close the application at the end, the error message (3) appears.
Is the data safe? Is it possible to recover from this?

(1)
![image](https://github.com/ShootMe/FallGuysStats/assets/117301922/eebcd6dd-08b5-4271-bbbb-04a480b25f7d)
(2)
![image](https://github.com/ShootMe/FallGuysStats/assets/117301922/0fea3925-2d3e-4561-a863-9a1208877b67)

(3)
![image](https://github.com/ShootMe/FallGuysStats/assets/117301922/c36c83dc-b8ea-47e7-b337-d617720724a5)

[data.db.zip](https://github.com/ShootMe/FallGuysStats/files/14340328/data.db.zip)
[Player.log](https://github.com/ShootMe/FallGuysStats/files/14340316/Player.log)

### Platform

Steam

**Comment by qutrits** [comment]
[data.zip](https://github.com/ShootMe/FallGuysStats/files/14348642/data.zip)

Try it with this file.

**Comment by takkun-mint** [comment]
> [data.zip](https://github.com/ShootMe/FallGuysStats/files/14348642/data.zip)
> 
> Try it with this file.

Thank you!
I'm able to start it up now,
Is it safe to get an error like this?
It says in Japanese: "An object of type 'System.Int32' cannot be cast to type 'LiteDB.ObjectId'".
![image](https://github.com/ShootMe/FallGuysStats/assets/117301922/1ada4eac-e480-4b84-8cae-d30397beddc6)

**Comment by qutrits** [comment]
Download the new version 1.330 and check if there is a problem by running the exe file and data.db file in one place.

**Comment by takkun-mint** [comment]
> Download the new version 1.330 and check if there is a problem by running the exe file and data.db file in one place.

I re-downloaded and ran it with only the Data.db file and the exe file and it solved the problem.
Thank you for your response.
