### ISSUE TITLE
[Bug]: Round names incorrect in Playful Pioneers / Playful Pioneers Shuffle

### ISSUE THREAD

**Issue by FallGuysStatsStan** [ShootMe/FallGuysStats#327]
### What happened?

When playing the "Playful Pioneers Shuffle" or "Playful Pioneers" shows, the round names which are shown on the FallGuysStats overlay and recorded to the database do not always match the names of the rounds that were played. I first noticed this issue approximately on March 7, and have noted some specific examples below on March 9-11. The issue might just be caused by the round pool for these shows being updated and the new round names not yet being added into FallGuysStats. 

Rounds I noticed a discrepancy on:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="">
<link rel=File-List
href="">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Show   Name | Round actually played | Round recorded by FallGuysStats
-- | -- | --
Playful Pioneers Shuffle | Ramp It Up! | Castle Clash
Playful Pioneers Shuffle | Run Run Park | Latte Cats
Playful Pioneers Shuffle | Pixel Circuit____ | Playful Shuffle 50
Playful Pioneers Shuffle | Wild Dunes | Playful Shuffle 46
Playful Pioneers Shuffle | Pixel Circuit____ | Playful Shuffle 50
Playful Pioneers Shuffle | Overclocked | Playful Shuffle 45
Playful Pioneers Shuffle | Monochromatic Manic | Track Attackers System
Playful Pioneers Shuffle | Green Mountain | Run Run Park
Playful Pioneers Shuffle | Snow Style | Trupixel's Jungle Mash-Up
Playful Pioneers Shuffle | Love A Day | Playful Shuffle 55
Playful Pioneers Shuffle | Triple Trial | Tunnel Vizion!
Playful Pioneers Shuffle | Multi Leaper | Plat Guys
Playful Pioneers Shuffle | Milky Way | Summer and the Wonder Land of
Playful Pioneers Shuffle | Pocket Summit | Playful Shuffle 54
Playful Pioneers Shuffle | Cosmic Pipes | Duck Duck Go!
Playful Pioneers Shuffle | Trupixel's Jungle Mash-Up | ___ Mikuseru
Playful Pioneers Shuffle | Trees (Waterfall) | Triple Trial
Playful Pioneers | The Last Winter | Nautical Shamble
Playful Pioneers | Rainbow Highway | Skybound Raceway
Playful Pioneers | Rainbow Riptide | Love Parade
Playful Pioneers | Fall Stars | Monochromatic Manic

</body>

</html>

### Platform

Epic Games

**Comment by qutrits** [comment]
Try it in v1.353.

**Comment by FallGuysStatsStan** [comment]
Yes, this seems fixed - in my log, the placeholder names like 'Playful Shuffle 46' have been replaced by the actual names like 'Wild Dunes'. Thank you!
