### ISSUE TITLE
[Bug]: Run Exception: Invalid BSonExpression when converted from Linq expression: ...

### ISSUE THREAD

**Issue by ropbl4** [ShootMe/FallGuysStats#328]
### What happened?

I play FallGuys last time 16.oct.2023, then i get pause, then i try to play 11.mar.2024 and can't run FG Stats can't run after update, only show error (screen).

![image](https://github.com/ShootMe/FallGuysStats/assets/71985019/ce75ddc8-cafa-4167-bfe2-57cab6e3e187)

### Platform

Steam

**Comment by qutrits** [comment]
Please compress and send the data.db and data-log.db files.

**Comment by ropbl4** [comment]
[data and data-log.zip](https://github.com/ShootMe/FallGuysStats/files/14576924/data.and.data-log.zip)

**Comment by ATIKIN-GH** [comment]
> Please compress and send the data.db and data-log.db files.

i have this problem too (epic games)

**Comment by qutrits** [comment]
Update to v1.350 and give it a try.

**Comment by ATIKIN-GH** [comment]
> Update to v1.350 and give it a try.

now all good, but when i tried to reinstall tracker i lost a lot of pbs and some wrs times(

**Comment by ropbl4** [comment]
It works for me, thanks !
