### ISSUE TITLE
[Bug]: DB error was displayed and it stopped starting.

### ISSUE THREAD

**Issue by takkun-mint** [ShootMe/FallGuysStats#338]
### What happened?

The above error message was displayed and I was unable to start the system.
I am attaching the DB file as well.
Thank you in advance for your support.
![image](https://github.com/ShootMe/FallGuysStats/assets/117301922/717d69e3-e5bc-4ca2-8277-0af4c8f14ff6)
[data.zip](https://github.com/ShootMe/FallGuysStats/files/15208191/data.zip)

### Platform

None

**Comment by Micdu70** [comment]
Here's a "working" state for your database:

[data.zip](https://github.com/ShootMe/FallGuysStats/files/15210292/data.zip)

**Comment by takkun-mint** [comment]
Thanks for fixing it!
