### ISSUE TITLE
[Bug]: Program error after updating from v.1.367 to v1.369

### ISSUE THREAD

**Issue by 123JLaney123** [ShootMe/FallGuysStats#341]
### What happened?

Was working fine on 1.367, noticed 1.369 was out (no auto update when there should have been?) so I downloaded it, moved my data over, and this is what I get now. Clicking X just closes it for about a second then it reappears, so it's unusable.
Please see attached photo/file.

![image](https://github.com/ShootMe/FallGuysStats/assets/76238470/a99586b5-305e-42f3-a017-10f5b7ee90ae)

[data.zip](https://github.com/ShootMe/FallGuysStats/files/15257988/data.zip)

### Platform

Steam

**Comment by 123JLaney123** [comment]
Just saw 1.370 came out, it also happens with that version.

**Comment by qutrits** [comment]
Try [this.](https://github.com/ShootMe/FallGuysStats/actions/runs/9013166018/artifacts/1486782173)
https://github.com/ShootMe/FallGuysStats/actions/runs/9013166018

**Comment by 123JLaney123** [comment]
That seems to work, thanks!
