### ISSUE TITLE
Error Updating

### ISSUE THREAD

**Issue by danlee1025** [ShootMe/FallGuysStats#36]
![image](https://user-images.githubusercontent.com/6588796/95482076-bb101780-095b-11eb-865d-5816ed8a5405.png)

I get that error when updating, do I need to give it permission to something?

**Comment by ShootMe** [comment]
Try closing and reopening the program. If that doesnt work, just redownload the zip and just replace the exe with the new one.

**Comment by danlee1025** [comment]
Yeah I've just been redownloading the zip and replacing the exe, do I need to replace `LiteDB.dll` also?

**Comment by ShootMe** [comment]
You shouldn't need to no.
