### ISSUE TITLE
[Bug]: Overlay does not show any information

### ISSUE THREAD

**Issue by ropbl4** [ShootMe/FallGuysStats#374]
### What happened?

On previous week overlay stops showing any information (screen).
On last version too.
But 2nd PC didn't have this bug (different db).
If i start from empty db - no bug.

![Screenshot_1](https://github.com/user-attachments/assets/fd3c23da-27d2-4c38-b863-ea92faa8bad1)

[data.zip](https://github.com/user-attachments/files/17065971/data.zip)

### Platform

Steam

**Comment by Micdu70** [comment]
Found a little bug in code that's causing your issue, fixed by #375 ;-)

**Comment by Micdu70** [comment]
For the current version of the tracker, you can replace your **data.db** file by this one:

[working_data_for_v1.386.zip](https://github.com/user-attachments/files/17070556/working_data_for_v1.386.zip)
