### ISSUE TITLE
[Bug]: the new course levels deosnt get a leaderboard right away

### ISSUE THREAD

**Issue by spaceVast** [ShootMe/FallGuysStats#384]
### What happened?

i got good pb in the new halloween maps , it didnt get to the leaderboards or either new runs added. where the leaderboard rn got some ppl. not much. it`ll probably fill up quickly but hopefully u add the first 2 hours runs of the update to it. when it didnt count.

### Platform

None

**Comment by spaceVast** [comment]
can u use cloudseeker API for Knockout too? cause still not reading my runs @Micdu70

**Comment by Micdu70** [comment]
I'm working on it. ;)

**Comment by spaceVast** [comment]
nice glad u answered , yeah the bug like the picture u send for the current two course rounds of knockout , i tried deleting the past knockout games so it register new runs still didnt add to the leaderboard , im saying this cause if i send the data.db u will find every knockout game deleted from 8th october

**Comment by Micdu70** [comment]
I think I fixed your issue, download the tracker with my patches here => https://github.com/ShootMe/FallGuysStats/actions/runs/11352008039/artifacts/2059627261

**Comment by spaceVast** [comment]
yeah pretty fixed it (notification and has right color) only downside not counted to leaderboard :( 
do i need to open the tracker without the data.db?

**Comment by Micdu70** [comment]
You need to need to remove your data.db, you didn't have to remove "Knockout" shows either. Only new time you will made will be sent now.

**Comment by Micdu70** [comment]
Info: Only "Official" releases of the tracker can send time to leaderboard. You can replace my "patched" version with the "Official" v1.391

**Comment by spaceVast** [comment]
oh ok i`ll do that

**Comment by spaceVast** [comment]
wow problem solved like magic thanks for ur support and help
