### ISSUE TITLE
[Feature Request]: Add Treat Thieves & Knockout to shows drop-down in profiles

### ISSUE THREAD

**Issue by buckstah** [ShootMe/FallGuysStats#385]
### What is your request?

Is there a way to manually add these as shows or must it be done in the code? If in the code is it possible to add? I'd love to be able to automatically separate Knockouts and Treat Thieves into their own section.

**Comment by Micdu70** [comment]
It must be done in the code. What I suggest is to add a checkbox (option) to display all shows or only the currently suggested (user choice).

**Comment by Micdu70** [comment]
PR #386 is adding 7 shows in the "Linked Show" selection. ;)
