### ISSUE TITLE
[Bug]: The explore rounds won't detected by fall guys stats

### ISSUE THREAD

**Issue by Dhi20071** [ShootMe/FallGuysStats#388]
### What happened?

any other shows will work with fall guys stats but explore doesn't work and it doesn't change the round

### Platform

Steam

**Comment by Micdu70** [comment]
I can confirm this issue and the reason: This issue happens when the [FallGuysDB API](https://fallguys-db.pages.dev/creative) (used to get info about played creative maps) is blocking the requests from your IP.

**Comment by Dhi20071** [comment]
is it fixable??

**Comment by Micdu70** [comment]
The tracker should not stuck like this. The overlay should always display the creative map code if the FallGuysDB API doesn't return an expected result from the request.

**Comment by Dhi20071** [comment]
oh wait FallguysDB can't determine the creative code so that's why it's stucked??

**Comment by Dhi20071** [comment]
![image](https://github.com/user-attachments/assets/52b31248-77f2-4425-8fc8-9d33bb27663a)

cloudseeker seems to work

**Comment by Dhi20071** [comment]
wait you can use cloudseeker API it does work there 
![image](https://github.com/user-attachments/assets/2925894a-9ca7-4bf3-b075-0304f004ce90)

**Comment by Micdu70** [comment]
Yeah the tracker could use this API has a fallback API. 👍

**Comment by Dhi20071** [comment]
the creator is the only one can change it right?

**Comment by Micdu70** [comment]
Everyone can propose a change in the code by sending a Pull Request (PR). The owner of this repository may do modifications himself or not (of course ^^).

**Comment by Dhi20071** [comment]
is there anyways to change the API??

**Comment by Micdu70** [comment]
I'm working on it. ;)

**Comment by Dhi20071** [comment]
![image](https://github.com/user-attachments/assets/b69148d5-48d5-4a06-8be6-e35856a1f613)
oh I see

**Comment by Micdu70** [comment]
Sent PR #389 to add CloudSeeker API as a fallback API and even if both API are down, the tracker will not stuck anymore. ;)

**Comment by Dhi20071** [comment]
thanks!

**Comment by Micdu70** [comment]
Here's the tracker with my patches, you can safety replace your current version with this one => https://github.com/ShootMe/FallGuysStats/actions/runs/11323362454/artifacts/2051959561

**Comment by Dhi20071** [comment]
now it works 
![image](https://github.com/user-attachments/assets/b926c118-ec5e-4ead-b4ca-77a338a57f95)

**Comment by Dhi20071** [comment]
![image](https://github.com/user-attachments/assets/c4c77fd2-f383-4329-a919-8a4ee9df5c98)
