### ISSUE TITLE
[Bug]: Missing Profile Names

### ISSUE THREAD

**Issue by atssuj** [ShootMe/FallGuysStats#399]
### What happened?

I am not seeing drop downs in the profile list for the following Show Types / LTM's. I know they keep adding new ones.

- 4th Anniversary Party
- Frosty Frolics

### Platform

None

**Comment by Micdu70** [comment]
We can add **4th Anniversary Party** in the list but **Frosty Frolics** is a "creative rounds only" show => All these shows are merged in **Fall Guys Creative**.
