### ISSUE TITLE
Windows Defender Flags the .exe file as a Trojan

### ISSUE THREAD

**Issue by corbynj** [ShootMe/FallGuysStats#40]
Windows Defender is flagging the .exe as a Win32/Zpevdo.B Trojan.

When running: https://i.imgur.com/TWoeupu.png
When scanned: https://i.imgur.com/NkDngon.png

**Comment by bigpcjunky** [comment]
I also had this problem and Windows defender deleted the exe file.  I tried to download the zip again and it also flagged that and deleted the download.

**Comment by frds6283** [comment]
Same issue.

**Comment by blakekl** [comment]
Go to Start > Settings > Update & Security > Windows Security > Virus & threat protection. Under Virus & threat protection settings, select Manage settings, and then under Exclusions, select Add or remove exclusions. Select Add an exclusion, and then select FallGuystStats.exe

**Comment by HwerdnA** [comment]
this only happened starting today. I think the github download may have been hacked and had a trojan horse inserted.

**Comment by TriumphReturns** [comment]
Same Happened to me. What are the chances it's a real virus vs a false detection?

**Comment by bigpcjunky** [comment]
I'm leaning towards a false detection.  I'm pretty sure I updated and used the tracker around 1am without problem.  I also ran a scan with Avast.  I guess we can be sure if someone downloads and builds the source and compares the files.

**Comment by Eldorian** [comment]
Likely false detection. Last commit was 3 days ago and nothing there in the commit that is even close to being scary.

**Comment by Eldorian** [comment]
One of the possible solutions is adding the author and description in the assemblyinfo.cs

**Comment by Eldorian** [comment]
Yeah, I cloned the code and added in the AssumblyDescription and AssemblyCompany to some values and it stopped triggering it for me.

**Comment by ShootMe** [comment]
There is no virus in the program, would just be a false positive. I added more info to the AssemblyInfo as Eldorian suggested. So hopefully that helps.

**Comment by Eldorian** [comment]
@ShootMe the change allowed me to download it without triggering windows defender like it was earlier, so hopefully that helped.

**Comment by bigpcjunky** [comment]
Looks okay now.  I think you can close this issue after those changes.

**Comment by corbynj** [comment]
I downloaded the latest update, and it ran without triggering Windows Defender.
