### ISSUE TITLE
Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by VonGhoul** [ShootMe/FallGuysStats#41]
Windows defender has quarantined the exe since the last update (1.88).

**Comment by HwerdnA** [comment]
Just re download it

**Comment by bigpcjunky** [comment]
Looks like the latest Windows Defender definition files are flagging the new build which fixed the false reports from yesterday.  I submitted the files to Microsoft for analysis.

**Comment by VonGhoul** [comment]
> Looks like the latest Windows Defender definition files are flagging the new build which fixed the false reports from yesterday. I submitted the files to Microsoft for analysis.

Ok, cool

**Comment by bigpcjunky** [comment]
Just got word from Microsoft that they've removed the false detection so all you need to do is have Windows Defender update the definition files.

**Comment by VonGhoul** [comment]
Great! Thank you
