### ISSUE TITLE
Event mode round names too long

### ISSUE THREAD

**Issue by faumyian** [ShootMe/FallGuysStats#42]
The new event mode names are long and are clipping in the overlay.  Seems to happen only on Roll Out and Jump Club that I can tell.

![image](https://user-images.githubusercontent.com/71907271/96270106-d4831600-0f90-11eb-9b2f-5145a0e0e687.png)
![image](https://user-images.githubusercontent.com/71907271/96270129-db118d80-0f90-11eb-89f2-cb0af0c3d077.png)

I would rather them just show with the normal name on both the overlay and the stats page.

p.s. Thanks for all your work on this.

**Comment by ShootMe** [comment]
No problem. Taken care of in v1.89
