### ISSUE TITLE
Malwarebyes flagging FallGuysStats as Malware

### ISSUE THREAD

**Issue by j0npau1** [ShootMe/FallGuysStats#43]
Malwarebytes
www.malwarebytes.com

-Log Details-
Protection Event Date: 10/19/20
Protection Event Time: 6:53 PM
Log File: 4d0b04e8-1266-11eb-9add-3085a9a668dd.json

-Software Information-
Version: 4.2.1.89
Components Version: 1.0.1070
Update Package Version: 1.0.31644
License: Premium

-System Information-
OS: Windows 10 (Build 19041.572)
CPU: x64
File System: NTFS
User: System

-Blocked Malware Details-
File: 1
Malware.AI.1855200559, C:\Users\Jon\Desktop\FallGuysStats\FallGuysStats.exe, Quarantined, 1000000, 0, 1.0.31644, AE25E117CE7D8F2C6E941D2F, dds, 00947443, FBD032FB29C39B98677B8F9CBE82C5A4, 9C095E0575B87D2EBB24E9BBC5881CF3A161C31A19D23981595F88D0B8CFB677

(end)

**Comment by bigpcjunky** [comment]
The latest Windows Defender definitions flag the current version as Trojan:Win32/Zpevdo.B

I've submitted the files to Microsoft for analysis.

Something weird is going on.  AFAIK no problems with antivirus detection until about a week ago.  Could it be someone is manually reporting the program as malware on purpose?

**Comment by HwerdnA** [comment]
bicpcjunky that does actually seem like the most plausible idea, as there is no malware or anything harmful in this, as I've been using it for multiple months.

**Comment by Jaerin** [comment]
What is the need for NDI?  Isn't that a desktop sharing library?  The detection on Windows Defender says that it opens ports in the firewall.  I'm not sure any reason why it would need to do that.

**Comment by ShootMe** [comment]
NDI is used to send the overlay over the network if playing on one computer and streaming on another. But there is no port opening in the program. The only thing it does is open a web request to github to download the latest version when you update.

**Comment by Jaerin** [comment]
Seems to make sense to me, but I could see how that could be the source of the detection.

All I know is Windows Defender defined it as Trojan:Win32/Zpevdo.B
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fZpevdo.B&threatid=2147729093

My guess is another malware used the same code and this got picked up as a false positive.

**Comment by bigpcjunky** [comment]
I haven't gotten an email update from Microsoft yet but I think they removed the false detection from the local client definitions but it's still being flagged on the cloud.

I think you guys need to figure out another way to do the updates.  Maybe just do a notification and force the user to manually update.

**Comment by bigpcjunky** [comment]
I meant force the user to manually download and update files.

Most small developers like CPUID force users to download and install upgrades.  I think only 'Trusted' developers can get away with 'live' updates without getting flagged as possible malware.

**Comment by Jaerin** [comment]
I redownloaded it and rescaned and it doesn't seem to get picked up anymore.

**Comment by bigpcjunky** [comment]
I checked the submission to Microsoft again and this time cloud protection is green and doesn't list Trojan:Win32/Zpevdo.B but a couple of hours ago it was still flagged.  I still think the code needs to be changed to avoid future false detections.

**Comment by mojomech** [comment]
anyone still having this issue? i downloaded this yesterday and got the  Trojan:Win32/Zpevdo.B detected from my windows defender. is there a work around for this or has anyone experienced any problems from it other than it being detected? I really like this app but not enough to put my pc at risk

**Comment by frds6283** [comment]
Issue is back for me - Windows defender flags as a virus.

**Comment by Jaerin** [comment]
This is likely going to keep coming back every time it is updated.  Not
much they can do about it because some malware likely used the same library
to abuse as they are using for something.

**Comment by bigpcjunky** [comment]
I haven't been playing Fall Guys recently so haven't downloaded the new version.

As I mentioned above the code needs to be changed to remove the option of an automatic download/installation of an update.  I'm pretty sure that's the code that is being flagged as malware.    Just give the user and update notice and have them manually download a setup program to update the db files and program.  Trusted developers can do automatic updates after a click but malware programs get people to click 'ok' to download & install viruses.  A level of protection is added if the user has to manually download and install a program.

As for a workaround you can go the Windows Defender page and click virus & threat protection settings and then manage settings and setup exclusions.   You can also go to protection history and allow the item that was flagged.

**Comment by ShootMe** [comment]
Added another DL option on the main page Readme. It has no auto update feature and in turn will just bring you to github if you click the button. This hopefully will fix the false positives for people having that issue.

**Comment by bigpcjunky** [comment]
Yeah, Windows Defender flagged the download of the auto update version but allowed the new manual update version.  I think that confirms that auto update was causing the problem.  

Honestly I think the auto update version should be removed or try contacting the Windows Defender team to find out how to 'properly' do auto update so it won't keep getting flagged as malware.
