### ISSUE TITLE
Default main window size

### ISSUE THREAD

**Issue by Icehawk217** [ShootMe/FallGuysStats#44]
v1.8.7 added functionality for the main window to be resizable.  However, these adjustments are not maintained through closing and reopening the program.

Can the window size settings, after adjusted by the user, be saved such that the main window will reopen at those same size settings?

Additionally, I think ideally the main window default size should be a length such that all games are visible, with no scroll bar.

**Comment by ShootMe** [comment]
I've added the ability to save the forms sizing, and as such I don't see any reason to default it to show all Levels since they are going to continue to add more and more levels.
