### ISSUE TITLE
Question about data.db

### ISSUE THREAD

**Issue by elanjcoop** [ShootMe/FallGuysStats#46]
I am trying to create a program in C# and LiteDB (both of which i know nothing) where I query the data.db database you created. any idea why this fails?
![Screenshot 2020-10-28 194603](https://user-images.githubusercontent.com/71735710/97508595-5e01f300-1956-11eb-8e70-57479b157ce9.png)

**Comment by ShootMe** [comment]
In the case for this table (RoundDetails) the Id field is not an int32. It is a LiteDB specific object called ObjectID. So if you change int to LiteDB.ObjectID it should work.

**Comment by elanjcoop** [comment]
You da best.
