### ISSUE TITLE
Rounds variations issues

### ISSUE THREAD

**Issue by soulpetsrevolution** [ShootMe/FallGuysStats#47]
![1605090124623292282084685725798](https://user-images.githubusercontent.com/49232079/98800097-e3070500-244a-11eb-9fe4-8365d8b9f9e6.jpg)

Its showing round_gauntlet_04_Variation_01 in the log, is there anyway to intregate the names into the normal ones?

This on Medieval Mix Up

**Comment by soulpetsrevolution** [comment]
Looks like i made it work :p

**Comment by soulpetsrevolution** [comment]
Looks like i did fix on my side

**Comment by ShootMe** [comment]
Should be taken care of in v1.92
