### ISSUE TITLE
Any chance of a more customizable overlay?

### ISSUE THREAD

**Issue by rafaelgomesxyz** [ShootMe/FallGuysStats#48]
It would be nice if we could customize the overlay a bit more. Specifically, I have 2 things in mind:

* Ability to make the overlay smaller by using icons instead of labels. For example, "WINS" could be a crown. As it is right now, it takes too much space in the screen.
* Ability to show only one of the cycled info. For example, I don't care much for number of players, but I like seeing my ping, so I wish the ping would be visible at all times instead of cycling.

Thanks for this awesome tool, by the way! I love seeing the stats.

**Comment by ShootMe** [comment]
I'm not a UI artist or even close, so taking on feature #1 would be a bit much for me so that won't happen anytime soon.

As for the 2nd feature, I just added it to the settings in v1.98

**Comment by rafaelgomesxyz** [comment]
No worries, thank you for implementing the second feature.
