### ISSUE TITLE
against  EULA fall guys 

### ISSUE THREAD

**Issue by butter234** [ShootMe/FallGuysStats#5]
I dm a @ fallguysupport about this "Hey there!

Thanks for writing in! My name is Chick-kun and I appreciate you bringing this to our attention.

Regarding your question, if this is considered cheating, please be aware that modifying and or gathering any file or any other part of our Service that we do not specifically authorize you to modify is strictly prohibited. Any further infractions may result in actions taken against the violator's account.

For more details, please check our Rules of Conduct included in EULA: https://fallguys.com/eula
For now, I will advise you to avoid using this and I'll be sure to bring this up with the rest of the team.

Have a nice day~! ^__^   https://i.gyazo.com/2c6ecb5976e5387841f691a2d7dd20f5.png

**Comment by ShootMe** [comment]
This program does not alter or modify any game files, it doesn't touch the process either.
It reads a file in your user directory created by the game.

So I would imagine it is just fine, but I am not a lawyer and you should use this program at your own risk.
