### ISSUE TITLE
Update Northernlion levels

### ISSUE THREAD

**Issue by danlee1025** [ShootMe/FallGuysStats#51]
![image](https://user-images.githubusercontent.com/6588796/99718934-a609c680-2a79-11eb-97fd-3d5e20f6e335.png)

I know the `1.95` update fixes this for future rounds, any way to update the rounds that already got added?

**Comment by ShootMe** [comment]
1.95 should fix existing levels as well. If you are on 1.95 then Im not sure what happened that it didn't update those. Let me know.

**Comment by ShootMe** [comment]
Never mind, looks like I had a typo in the portion that updates the existing levels. Should be fixed in v1.96.
