### ISSUE TITLE
Not logging data

### ISSUE THREAD

**Issue by mngshan** [ShootMe/FallGuysStats#53]
For some reason the program stopped logging new shows. It still displays the data for the ongoing show correctly, but does not log the data. Not sure what I did to cause this. I have tried downloading a fresh copy with the data.db copied over but it still does not log new data.

**Comment by ShootMe** [comment]
Not sure exactly. If you just mean the new game mode shows then that would be because they don't show up as a normal level until I get around to add them.

Try v1.98 and let me know

**Comment by mngshan** [comment]
Seems to be fixed now. I guess it must be some issue with state then that I caused by copying data.db around. In the future then I should probably just update it with the built-in update feature?
