### ISSUE TITLE
Suggested Program to Manually Correct New Game Mode Names // Small Request

### ISSUE THREAD

**Issue by angui82** [ShootMe/FallGuysStats#54]
Hello!

First of all, many thanks for writing this program, I've been using for the last week, and it's been great.

As you can imagine, the new game mode is "creating waves" as the levels in it do not share names with the "normal" rounds eventhough they are the same (e.g. "Gaunlet 04 Event Yeetus" instead of "Knight Fever").

My first thought was to find a LiteDB editor to open the DB and manually correct them. Is there anyone that you would suggest?

After that, I took a look here and found that this is something you've had to patch everytime a new show, shows-up, that is why I think being able to manually update it could be an option I could learn.

Finally, I see someone also already brought this point up, and I would like to let you know that if possible, I would appreciate if you could work on it as well, that is, "the ability to show only one of the cycled info. For example, I don't care much for number of players, but I like seeing my ping, so I wish the ping would be visible at all times instead of cycling. ", that felt as if I writed it my self.

Once again, many thanks for your awesome tracker, I appreciate the time you've put into this.

Fer Anguiano

**Comment by ShootMe** [comment]
Hey there! Yea it's unfortunate that the game modes for whatever reason add post fixes on the round names causing issues with the stats. I just add an update for them each time something new pops up.

And I went ahead and added the ability to select the alternate option for those 4 fields on the overlay in the settings in v1.98

**Comment by angui82** [comment]
Hello!

       Thanks a lot for the extremely quick response! Specially on a Sunday!

       I’ll give it a try soon!

       Once again thanks for your support! I really appreciate it!

Kind Regards!


________________________________
De: DevilSquirrel <notifications@github.com>
Enviado: domingo, 29 de noviembre de 2020 13:10
Para: ShootMe/FallGuysStats <FallGuysStats@noreply.github.com>
CC: angui82 <angui_82@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [ShootMe/FallGuysStats] Suggested Program to Manually Correct New Game Mode Names // Small Request (#54)


Closed #54<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FShootMe%2FFallGuysStats%2Fissues%2F54&data=04%7C01%7C%7C1fa98ae888984600607508d8949a7782%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637422738426144045%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YYaGwlVtVzxnctPzpqmeKMgQIaVlKSiqIasInd7LsGQ%3D&reserved=0>.
