### ISSUE TITLE
Big Yeetus Mode - Fall Mountain Final Problem

### ISSUE THREAD

**Issue by angui82** [ShootMe/FallGuysStats#55]
Hello again Devil Squirrel!

I wonder if you received my response mail, but if not, in short I thanked you for the really quick response (specially on a Sunday!) to my previously raised issue.

Most of the update looks fine, except for two things I've noticed:

1.- Although the Yeetus Fall Mountain Final has been renamed correctly, it is still not recognized as a "Final" (red) by the tracker itself, but rather, as a "new" (grey) kind of round. (Picture 1), it doesn´t even have the check on the table (Picture 2)

2.- Furthermore, if you win it, it doesn´t count towards the "Total" wins shown on the overlay (although it IS recognized as such in the generated graph) (Picture 3).

Once again, many thanks for creating the tracker, and taking the time to keep updating it.

Do not hesitate to contact me if furher information is requiered.

Kind Regards!

![Picture 3](https://user-images.githubusercontent.com/75210515/100569227-03c8ba80-3293-11eb-8c93-2559e7530a22.PNG)
![Picture 2](https://user-images.githubusercontent.com/75210515/100569230-04615100-3293-11eb-9f4b-81b7cffd1671.PNG)
![Picture 1](https://user-images.githubusercontent.com/75210515/100569232-04615100-3293-11eb-9e2f-eb70429eaa70.PNG)

**Comment by ShootMe** [comment]
Interesting, the win count is just because it's not recognized as a normal level. As to why that is, I'm not sure since I haven't had much time to play the game myself. If possible can you attach your data.db file zipped up?

**Comment by angui82** [comment]
Sure thing! Please find it attached and let me know if I can help in any way. Thanks for your support and quick responses!

[data.zip](https://github.com/ShootMe/FallGuysStats/files/5619377/data.zip)

**Comment by ShootMe** [comment]
Weird, here is your db fixed. If it happens again Ill fix it in code, but Im thinking this was a one time thing.
[data.zip](https://github.com/ShootMe/FallGuysStats/files/5619512/data.zip)

**Comment by angui82** [comment]
Holy! Thank you very, very much! Hope it is indeed a one-time thing and I do not neeed to bother you again. Do you have a "buy me a coffe" account or something similar? Kind Regards!

**Comment by angui82** [comment]
Forgot to mention, it seems it's working properly now.
Regards!

**Comment by Kazumin7** [comment]
I've actually encountered the same problem with fall mountain. It might be due to playing the yeetus gameshow before the update to the stat tracker which addressed it?
[datazip.zip](https://github.com/ShootMe/FallGuysStats/files/5619753/datazip.zip)


![image](https://user-images.githubusercontent.com/67619222/100686370-08dd4680-3333-11eb-8c02-771a05face02.png)

**Comment by ShootMe** [comment]
Must have been a wide spread issue then. It should be taken care of in v1.99, and hopefully game modes don't mess things up anymore with this change.
