### ISSUE TITLE
Not updating games

### ISSUE THREAD

**Issue by ItsMeMDV** [ShootMe/FallGuysStats#58]
I wanted to delete a show because I got disconnected from the server but after I deleted the show This messege keeps appearing and whenever I close it it comes back in like 2 seconds. My stat tracker does update but I don't know how to get rid of this error messege.

![](https://cdn.discordapp.com/attachments/611465972309819415/789410931981156352/unknown.png)

**Comment by ShootMe** [comment]
If you are not on v1.101 then just download the zip again and just copy the exe from the zip to replace the exe from the directory you have it in now. If that doesn't fix it upload your data.db file here and ill take a look

**Comment by MrNutzer** [comment]
Sorry to hijack this thread, but as I have the exact same error message, I'm assuming it concerns the same error, although I have not deleted any shows, as OP had. I have updated to v1.101 but that does not seem to have fixed the issue.

Apparently uploading .db files is not possible here, so I had to put it in a zip file (I hope it worked).
Would be happy to hear if you have a solution to the error.

[data.zip](https://github.com/ShootMe/FallGuysStats/files/5717633/data.zip)

**Comment by ShootMe** [comment]
Everything looks fine on my end and Im not getting any errors with it. Do you use English as your game language? or something else?

If you could try going to C:\Users\<Your User Name>\AppData\LocalLow\Mediatonic\FallGuys_client
and uploading the Player.log and Player-pre.log if they exist here as well? 
There must be something specific you are getting in your log file that I haven't seen before causing an issue.

**Comment by ShootMe** [comment]
Update to v1.102 to see if that fixes it.

**Comment by MrNutzer** [comment]
Thank you for the quick fix ShootMe, v1.102 indeed seemed to fix it!
