### ISSUE TITLE
Repeated error message when opening fall guys stats

### ISSUE THREAD

**Issue by MCHAWKING-cpu** [ShootMe/FallGuysStats#59]
Love the app. Just started getting this issue an hour ago after using the app for a week where the following message pops up when I open the app and continues to pop up when I close it:

System.NullReferenceException: Object reference not set to an instance of an object.
 at FallGuysStats.LogFileWatcher.ParseLine(LogLine line, List 1 round, String& currentPlayerID, Boolean& countPlayers, Boolean& currentlyInParty, Boolean& findPosition, Int32& players, RoundInfo& stat, Int32& lastPing, Int32& gameDuration, Boolean& privateLobby)
 at FallGuysStats.LogFileWatcher.ParseLines()

I tried downloading a new version of the app but get the same message. Any suggestions?

**Comment by ShootMe** [comment]
Same issue as #58 , my last statement to them as well:

If you could try going to C:\Users\Your User Name\AppData\LocalLow\Mediatonic\FallGuys_client
and uploading the Player.log and Player-pre.log if they exist here as well.
There must be something specific you are getting in your log file that I haven't seen before causing an issue.

**Comment by MCHAWKING-cpu** [comment]
[Data.zip](https://github.com/ShootMe/FallGuysStats/files/5718234/Data.zip)

Sorry about that didn't realize the previous thread was the same error from the title. The app was working perfectly fine this morning.

**Comment by ShootMe** [comment]
Thanks for the upload, was able to figure it out from that.

Must have been from a disconnect or early game leave? Wonder if there was a bunch of server issues today or something? Looks to be because the server is sending you episode complete status right when you are joining a game which is throwing off the parsing logic.

Download the new version v1.102 which should fix it.

**Comment by MCHAWKING-cpu** [comment]
Thanks very much. Before I download v1.102 (I'm not able to update from the app because the error prevents everything), is there a way I can preserve my data from this version so I keep my stats? Like can I move my data file from the old app folder to the updated app folder?

**Comment by ShootMe** [comment]
Just download the new zip and take the exe out of it and copy it to your existing folder and it will be updated

**Comment by MCHAWKING-cpu** [comment]
Great thanks. Seems to be working now. Cheers.
