### ISSUE TITLE
Running under Linux

### ISSUE THREAD

**Issue by SolidTux** [ShootMe/FallGuysStats#6]
Hi,

I'm running Fall Guys with Proton. The FallGuyStats.exe start without an error and the overlay is show as well when activated. But no stats are collected. What can I do to do some more troubleshooting? It looks like the `player.log` file is in the correct folder.

**Edit**

Judging from `strace`, it tries to open the log file in `steamapps/compatdata/1097150/pfx/dosdevices/c:/users/steamuser/Local Settings/Application DataLow/Mediatonic/FallGuys_client/Player.log`, but the file actually lies in `steamapps/compatdata/1097150/pfx/pfx/dosdevices/c:/users/steamuser/AppData/LocalLow/Mediatonic/FallGuys_client/Player.log`.

**Comment by ShootMe** [comment]
I don't have much experience with Linux, but I do plan to add a settings screen soon with a bunch of options.
I may try adding a way to set the location then, which hopefully will take care of it.

**Comment by SolidTux** [comment]
That would be great! For now I just made a symlink and everything seems to work fine.
