### ISSUE TITLE
v1.102 not recording shows

### ISSUE THREAD

**Issue by 123JLaney123** [ShootMe/FallGuysStats#60]
Shows up live in overlay but nothing is recorded in the app.  Both shows.

**Comment by MCHAWKING-cpu** [comment]
Experiencing same issue. If I close the app and reopen it, then it will say I have previous shows not in current stats which will add in the missing shows however it does not automatically update the stats without the restart as it had done previously.

**Comment by OpenBox3D** [comment]
for me, it shows all the shows current status but does not update finals

**Comment by ShootMe** [comment]
Sorry about that, looks like the live stat generation got messed up with 102. I only tested against an existing log file which was working but forgot to test a live round as well. Is fixed in v1.103, made sure to test both.

**Comment by MCHAWKING-cpu** [comment]
Everything seems to be working normally now. Thanks again.
