### ISSUE TITLE
Several little enhancements

### ISSUE THREAD

**Issue by hunterpankey** [ShootMe/FallGuysStats#61]
Hi friends, I've recently pulled the repo and made a bunch of little quality of life enhancements that I think would help things out:

* Move top labels into a true toolbar to aid in layout management.
* Clicking a level name opens level details like clicking the info icon.
* Clicking elsewhere in the grid toggles percentage display like clicking the win % heading label, so the odd UX path of clicking the "Win %" label to toggle level percentage displays isn't necessary.
* Added a "Grid Display" button to toolbar to explicitly set count vs. percentage displays.
* Pressing escape while viewing Level Details or Stats Display closes the window, i.e., user does not have to click the X or press Alt-F4 to close these sub-screens.
* Refactor some event handlers so they can be triggered from multiple locations more easily, i.e., clicking label, clicking other button, clicking menu item can call the same code from each location for maintainability.
* Added a setting option to ignore the game type when sorting the grid. I frequently want to see what my fastest time is regardless of type, and sorting within types frustrates that.
* Add a toolbar button to launch the Fall Guys game by dynamically finding the steam install folder and locating the game exe within the configured Steam library locations.
* Add settings to manually locate the Fall Guys exe if auto-detection fails.
* Add setting to auto-launch Fall Guys on stats tracker start, so users can just fire up the tracker and end up in the game.

@ShootMe and others, is this stuff useful? I'm happy to send over a PR if you're interested in taking a look...

**Comment by ShootMe** [comment]
You can send a PR and Ill take a look through it. As long as there are no major changes I would probably accept it.

**Comment by hunterpankey** [comment]
OK, I'll merge everything up and send it over. I'm playing a couple of hours to test things out, too.

**Comment by hunterpankey** [comment]
Got a 403 Forbidden when creating the PR, so I probably just don't have access to the right things.

**Comment by ShootMe** [comment]
Did you try to PR this repo by chance? You would have to commit to your fork first and from there create a PR to this repo.

**Comment by hunterpankey** [comment]
Good call! I don't know why I thought I'd be able to PR from within your repo. 😀 

Do you have a backlog or anything? I thought about a temporary overlay that fades in as you approach your best level time or average level time, showing the local finish times as you progress through them. Etc, etc. I have like a million ideas...

**Comment by ShootMe** [comment]
Currently, I don't have anything specific to add. Pretty much just keeping it up to date with new levels as they come out is about all. I'm open to most changes if you ever add anything else though.

**Comment by hunterpankey** [comment]
Looking good!
