### ISSUE TITLE
Add overlay to Streamlabs OBS

### ISSUE THREAD

**Issue by AnnyongNewman** [ShootMe/FallGuysStats#64]
Sorry if this was addressed previously but I am looking for a way to add your tracker to my Streamlabs OBS. Specifically, I would like to add the overlay that is available. I love all the detail it provides! Please let me know if there is a way to do this that you are aware of

thank you!

**Comment by ShootMe** [comment]
You should just be able to Window Capture it. You can set the background color (In settings) to something easy to chroma key out as well, like green.

**Comment by AnnyongNewman** [comment]
Sounds good. I will do just that. Didn't know if there was another way. Thank you for the quick response!
