### ISSUE TITLE
Average times broken?

### ISSUE THREAD

**Issue by 123JLaney123** [ShootMe/FallGuysStats#66]
On some levels it seems fine (haven't bothered to manually check every level one by one). But at a glance, on some others there is clearly an issue. For example, on Royal Fumble the level **always** lasts 1:30, no early elimination or overtime is possible, yet the average says 1:07.50. Strangely this affects the all time filter but not the week/season filter for me. And my average time on Fall mountain/Tail Tag/Team Tail Tag is less than possible also. Again, which filters are chosen affects if it is broken or not.

**Comment by ShootMe** [comment]
Looks like I was including all rounds into the calculation, so it was counting times when you didn't finish the round dropping the time. Is fixed in v1.107

**Comment by 123JLaney123** [comment]
Thanks
