### ISSUE TITLE
unable to delete shows

### ISSUE THREAD

**Issue by OpenBox3D** [ShootMe/FallGuysStats#69]
the recent Hex-a-Gone trails only shows are messing up the stats as it is counting each of the 2 qualifying round as wins.

tried going into the level stats to delete the shows but delete option is not available.

![Screenshot (901)](https://user-images.githubusercontent.com/9343277/103651210-32c20280-4f9c-11eb-87b2-8b82c1b82116.png)

**Comment by knightry** [comment]
Just click the row you want to delete and press the delete key. Worked fine for me.

**Comment by ShootMe** [comment]
Working on a fix. Is just a display issue, don't worry about the numbers being incorrect will resolve once I get the fix out for it.
As for the delete show you have to be on the show stats screen not level stats.

**Comment by ShootMe** [comment]
Should be fixed in v1.108
