### ISSUE TITLE
Background layer appears behind tracker

### ISSUE THREAD

**Issue by hayes2419** [ShootMe/FallGuysStats#71]
This started about a week ago, but the gray background layer now appears underneath the tracker. Some people are using a Chroma Key work-around, but it would be nice for this layer to be transparent again. 

<img width="527" alt="Screen Shot 2021-01-10 at 3 46 08 PM" src="https://user-images.githubusercontent.com/26581714/104135005-4504bd80-535b-11eb-9c3c-fa70d867b888.png">

**Comment by ShootMe** [comment]
Thats how it has always been if you are capturing the window itself in OBS. You have to chroma key it out to have it transparent or use desktop capture
