### ISSUE TITLE
Shows no longer being recorded in v1.109

### ISSUE THREAD

**Issue by rollins31** [ShootMe/FallGuysStats#72]
The tracker does seem to sync up with the game in progress and show stats for the round being played, but the shows and rounds are no longer being recorded in the tracker after they are done. I did have one show where I won but the Fall Guys server apparently did not record the win (I hung on the post-game loading screen for a long time and eventually was told that the game didn't get any record at the time but any prizes would be rewarded to me later) so that may be a cause, although I'm not 100% sure.

Looking through my shows list I also saw that the tracker flipped to the next day on its own by mistake as shown in the screenshot below. Again, not sure if related but including just in case.

Including my data.db if it helps.

![image](https://user-images.githubusercontent.com/77420528/104530253-e8e9b400-564e-11eb-890b-882f34cf8030.png)

[data.zip](https://github.com/ShootMe/FallGuysStats/files/5811787/data.zip)

**Comment by ShootMe** [comment]
Interesting, your log file must have had a weird entry that caused it to think a day passed during that show. I've updated the log parsing to hopefully fix that from happening again and updated your data.db file to have the correct dates.
[data.zip](https://github.com/ShootMe/FallGuysStats/files/5811906/data.zip)

**Comment by rollins31** [comment]
Thanks! Dates look good and we are recording games again.
