### ISSUE TITLE
Google Chrome detecting repository as dangerous

### ISSUE THREAD

**Issue by rainyillusionist** [ShootMe/FallGuysStats#74]
So I was trying to access the repo on a daily basis, and Google Chrome showed me this today when I went directly to the repo link.

![image](https://user-images.githubusercontent.com/16099962/104921661-999bde80-59d4-11eb-9dde-ff0907f91b9d.png)

I understand that you have a manual update zip file in case of false positives, apparently Chrome is blocking both files from being downloaded apart from that warning as well. These are just my observations.

Separately, the tracker version with the auto-update got auto-deleted by Windows Defender 1 or 2 days back, probably their virus definitions got updated or something?

**Comment by ShootMe** [comment]
I've updated the program to try and remedy this as well as requesting google to remove the unsafe marker. Hopefully it works out.
