### ISSUE TITLE
v1.111 Snowball Survival

### ISSUE THREAD

**Issue by 123JLaney123** [ShootMe/FallGuysStats#76]
Thanks for the 112 update, but I've noticed the pre-app-update rounds of the new round are added as a new round. I assume they can be converted as was the case in previous updates when new rounds were added?
![Screenshot 2021-02-02 171602](https://user-images.githubusercontent.com/76238470/106637268-5fa50d80-657a-11eb-88f6-c46afa5c8a6b.jpg)

**Comment by ShootMe** [comment]
Should be fixed on v1.113

**Comment by 123JLaney123** [comment]
Thanks
