### ISSUE TITLE
Snowball Survival stats in overlay don't show up properly

### ISSUE THREAD

**Issue by knightry** [ShootMe/FallGuysStats#77]
Seems to be related to the recent update truncating the name of the round in the overlay. The underlying tracker shows my data correctly, but the overlay always shows 0 games played (despite playing 20+ games).

**Comment by dungi** [comment]
Can confirm

**Comment by ShootMe** [comment]
Should be fixed in 1.114

**Comment by dungi** [comment]
Yes, is fixed. can be closed
