### ISSUE TITLE
Snowball Survivor no longer tracks qualify rate.

### ISSUE THREAD

**Issue by ApacheThunder** [ShootMe/FallGuysStats#78]
After latest commit that fixed name position on overlay it seems to no longer have correct qualify rate for me. (it reset to zero). I had to roll back to the previous version to avoid this issue. The data perhaps was not moved correctly when it was moved in the graph page? I won't update unless this data is correctly moved over.

**Comment by ShootMe** [comment]
There is no issue with the data in 1.113, is just a display issue with the overlay. The overlay was just using the wrong name when trying to query the stats. v1.114 should fix it

**Comment by rainyillusionist** [comment]
I believe this should also fix the Hoopsie Legends not tracking stats as well on the overlay? Haven't got that round yet since the push; I noticed Hoopsie Legends' round name was truncated off as well, might have been the issue why it wasn't tracking.

**Comment by ApacheThunder** [comment]
Oh yeah I didn't notice if it tracked in the main window. Was an overlay issue. If it's fixed in latest build I'll close this issue then.
