### ISSUE TITLE
Suggestion: Switch between win ratio with total shows / finals in overlay?

### ISSUE THREAD

**Issue by grace019** [ShootMe/FallGuysStats#84]
The WINS ratio is now calculated by the total shows as a denominator.  Which tells me how well I did to get a crown within the total shows.  I'd personally like to know how well I did specifically in finals.  While I agree on having a total WINS ratio that we have now, I would like to switch between WIN ratio with denominator as total shows and total finals.

I have added this function on my local build and using it without any problem but would like to have it on this so that I don't need to add the function when future releases come out.

I'm very new to GitHub but can I just create a branch or do I need consensus / approvals first?

**Comment by ShootMe** [comment]
You would create a fork of this repository, make your changes and commit to your fork. Then you create a pull request back to this repository, at which point I would look through your changes and include it or not. As long as it's nothing major I would usually include it.

**Comment by grace019** [comment]
Thank you for the kind answers, I tried creating a pull request just now.  Please take a look when you can.

**Comment by grace019** [comment]
Would close this.
