### ISSUE TITLE
Season 4 alternate shows

### ISSUE THREAD

**Issue by 123JLaney123** [ShootMe/FallGuysStats#87]
Same issue as with other seasons, just needs correcting. 

![image](https://user-images.githubusercontent.com/76238470/112023204-f037ad00-8b2a-11eb-9397-77d2447a2ba4.png)

**Comment by ShootMe** [comment]
Can you upload the Player.log / Player-prev.log file from AppData LocalLow Mediatonic FallGuys_client ?
Need to make sure of the names and I can't test squads myself

**Comment by 123JLaney123** [comment]
[Player.log](https://github.com/ShootMe/FallGuysStats/files/6183852/Player.log)
[Player-prev.log](https://github.com/ShootMe/FallGuysStats/files/6183853/Player-prev.log)
I think that's right

**Comment by ShootMe** [comment]
Dang, it must have been in one of your earlier sessions.
I think I can get the info from the data.db file though if you can upload that

**Comment by ShootMe** [comment]
Well I think I figured it out regardless. Try 1.116

**Comment by 123JLaney123** [comment]
Yeah the S4 maps showed up before S4 for some reason. Also you fixed it regardless, thanks.
